### ISSUE TITLE
Add support for HostEurope

### ISSUE THREAD

**Issue by nilsbyte** [AnalogJ/lexicon#103]
It's no pure DNS provider, but a big provider for webhosting worldwide. What are the chances to add HostEurope support?

**Comment by AnalogJ** [comment]
Hey @nilsbyte 
 Unfortunately I don't have a an account with HostEurope myself so it's hard to write one for their API,  but I'd be willing to merge a PR.

Here's a link to the [CONTRIBUTING.md](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md) if you're willing to contribute one :)
