### ISSUE TITLE
function update_record() in namesilo.py has wrong query parameter

### ISSUE THREAD

**Issue by wouck** [AnalogJ/lexicon#105]
origin: data['rdata'] = content
modified: data['rrvalue'] = content

**Comment by AnalogJ** [comment]
hmm, thanks for this. Are you referencing line https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/namesilo.py#L78 ?

**Comment by wouck** [comment]
Sorry for the late. You've fixed it, thank you!
