### ISSUE TITLE
DreamHost Provider only works if root domain is set with an A or AAAA record

### ISSUE THREAD

**Issue by JerrettDavis** [AnalogJ/lexicon#1064]
I'm using Lexicon to generate certificates an environment where DNS is my only accessible option, but I've noticed an odd behavior. It appears that it'll only successfully authenticate a domain if the `@` entry has an `A` or `AAAA` record defined in DNS. This is a bit problematic in my environment as I have a CNAME pointed towards hashnode setup for that entry.

Is there any reason why a CNAME would not be regarded as valid for the purposes of authenticating the domain? You can see the behavior defined below.

https://github.com/AnalogJ/lexicon/blob/18c788dc410b0088336ee1c392f63102fe956ed4/lexicon/providers/dreamhost.py#L109-L112

**Comment by chhsiao1981** [comment]
hi @JerrettDavis ～

Sorry for the late of response.

1. I'm so sorry that I missed "CNAME". I can add it back to the code as well.
2. Dreamhost actually changed their API in Nov. (without any official announcement). Basically they retired majority of the APIs, including all the update-related APIs. The module won't work anymore.

![image](https://user-images.githubusercontent.com/2970164/151809185-19ceda51-34cd-4d68-b2a2-eaf66d1b8c1a.png)

**Comment by chhsiao1981** [comment]
A follow-up from Dreamhost confirmed that the APIs that we are using (dns-add_record and dns-remove_record and dns-list_records) are still working.

I'll update the code and include CNAME

![image](https://user-images.githubusercontent.com/2970164/151810331-3ac0522b-f94c-4103-bfc7-d62680722321.png)

**Comment by JerrettDavis** [comment]
@chhsiao1981 Thanks for following up on this, and I'm glad to hear it was an oversight rather than a functional limitation.

I'm more than happy to push a PR to correct this if you've got some stuff stacked up on your plate.

**Comment by chhsiao1981** [comment]
hi @JerrettDavis ～

thanks!

welcome PR!

**Comment by chhsiao1981** [comment]
Looks like this issue has been resolved by #1110

**Comment by JerrettDavis** [comment]
Closed with #1110
