### ISSUE TITLE
trying to develop a new provider

### ISSUE THREAD

**Issue by txr13** [AnalogJ/lexicon#113]
I'm a total newb at Python... but I really need that GoDaddy provider, so I thought I'd start trying to bang something together.

After following the instructions in [CONTRIBUTING](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md), I found that none of the changes I was making to source seemed to be taking effect. I'm not sure I've actually found the issue (because I'm a newb with Python, and I find this all very confusing!)... but after review, I noticed that running `pip install -r optional-requirements.txt` seems to also run `python setup.py install` as part of the process.

Does this take effect over the later command of `python setup.py develop`, or does the later command overwrite the effects of the previous install?

**Comment by AnalogJ** [comment]
Woah, I really thought I had responded to this, sorry about that. 

I updated the contributung guide. You should try `pip install -e .` instead.

**Comment by AnalogJ** [comment]
Hey @txr13 
Did that work for you?

**Comment by txr13** [comment]
Hi @AnalogJ! Sorry, I saw the change, but I haven't had a chance to test it quite yet. (I just finished figuring out how to rebase my branch to integrate the updates that have taken place since I last touched it.)

But I just tested it now, and I confirm that my changes to the provider file are now visible. Thank you! I'll start trying to muddle my way through Python now... or in a couple weeks, when life stops smashing me in the head...

**Comment by AnalogJ** [comment]
Hey @txr13 
GoDaddy support was added in #131 [v2.1.8](https://github.com/AnalogJ/lexicon/releases) so I'll close this PR.

If you ever need help adding another provider, I'm around :)

**Comment by txr13** [comment]
Yeah, I completely failed at trying to write something up. But then, looking at the new provider, I'm not sure I would have figured it out on my own, either...

Thanks again for your assistance! Looking forward to using that new GD provider. :)
