### ISSUE TITLE
two part domain names

### ISSUE THREAD

**Issue by simonmcnair** [AnalogJ/lexicon#1235]
please can https://github.com/AnalogJ/lexicon/issues/353 be reopened as pynamecheap is no longer used and there are issues with handling two part domains such as .co.uk

I suspect this won't just apply to namecheap ?

Thanks :-)

**Comment by simonmcnair** [comment]
I have got this working, I think by modifying /usr/local/lib/python3.9/site-packages/lexicon/providers/namecheap.py ( https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/namecheap.py) 

I added:

import tldextract

and then replacing all the occurrences of:

        sld, tld = domain.split(".")

with:

        extracted = tldextract.extract(domain)
        sld = extracted.domain
        tld = extracted.suffix

**Comment by adferrand** [comment]
Closed by #1237
