### ISSUE TITLE
Namesilo throwing an exception on create if a record already exists

### ISSUE THREAD

**Issue by Tea23** [AnalogJ/lexicon#138]
The Namesilo provider halts with an exception on create if a record already exists. The comment suggests that it should be doing nothing if the record already exists.

Let's Encrypt dns-01 validation doesn't seem to work with wildcard A records, so the theory here is to have my hook create an A/AAAA record when issuing a cert. However the exception prevents this from being possible.

**Comment by AnalogJ** [comment]
hmm. I'll take a look at this. The test suite should already test for this usecase.
