### ISSUE TITLE
Route53: Public and Private Zones can't be distinguished.

### ISSUE THREAD

**Issue by erenfro** [AnalogJ/lexicon#142]
I've been testing out lexicon for updating DNS records via Route53, and I have a Public and Private Zone with the same domain name.
I noticed that lexicon is only searching for the domain name by name, so in my case, my internal zone was the first created and so it's the only thing lexicon itself finds for my domain name.

I was going to have it update a record for my home IP address for dynamic IP issues, but what's happening is it is only updating the Private zone's record. I've specified --identifier with the ZoneID of the Public Zone, but that is not working either.

I didn't even have a record for home.mydomain.com in my Private Zone, and it ended up creating the record just to fullfill the update. I do see in the output of lexicon both private and public zones, including the <PrivateZone>true|false</PrivateZone> specifically identifying it as private or not.

I'd like to be able to update both, differently as needed.

**Comment by Stollie** [comment]
I have the same problem.

I think the best option would be to implement the "--identifier" option for Route53.

`lexicon cloudflare delete www.example.com TXT --identifier="route53 ZoneID"`

Like the example of cloudflare
`lexicon cloudflare delete www.example.com TXT --identifier="cloudflare record id"`

I've made a fork and I hope to have time this week to make a pull request.

**Comment by AnalogJ** [comment]
@Stollie @erenfro Would the delegated domain work done in #136 help you guys?

**Comment by Stollie** [comment]
I'm using delegated domain to get "example.staging.example.org" data into the right Hosted Zone.
But r53_client.list_hosted_zones_by_name outputs:

| Domain name | Type | Record set count  | ZoneID|
|-----|----|-----|-----|
| staging.example.org. | Private | 7  | KFAOE |
| staging.example.org. | Public | 7  | ZAIA9 |

And lexicon will pick the first, this Hosted zone cannot be accessed by for example Let’s Encrypt .

**Comment by Stollie** [comment]
I have created a pull request to add the "--private-zone" argument. To only search for Private Hosted Zones when true and Public Hosted zones when false. Without the argument it just behaves as before.
