### ISSUE TITLE
Support for DnsMadeEasy internal ANAME record type

### ISSUE THREAD

**Issue by hontvari** [AnalogJ/lexicon#143]
An ANAME record in DnsMadeEasy is an alternative to CNAME records, it has the same format.

The difference is that ANAME is dynamically converted to an A record when the DNS server receives a query for the A record. It is a bit faster than CNAME, but its main advantage is that it can be used on the root of the domain. You cannot use a CNAME on example.com, but you can configure an ANAME on it. An ANAME record looks exactly like a CNAME record while it is defined in a zone file (or at least on the dnsmadeeasy UI). For example:
www.example.com. ANAME www1
example.com. ANAME www1

**Comment by AnalogJ** [comment]
Is the idea that you would want to create ANAME records? or just retrieve them?

**Comment by hontvari** [comment]
I would like to change the domain the ANAME record points to. For example there is an ANAME record, named www.example.com which points to proxy1.example.com. I would like to modify this record so that it will point to proxy2.example.com.

**Comment by AnalogJ** [comment]
Ah. In general the idea behind lexicon is to create a universal tool to modify and update DNS services. 

I think it would be interesting to support service specific customizations like this, but it would require a bit of re-architecting, and isn't possible with the current design right now.

**Comment by hontvari** [comment]
I understand, thank for the response. They submitted ANAME to IETF, https://tools.ietf.org/html/draft-ietf-dnsop-aname-00, but it does not seem to be active, it had been expired a few days ago.
