### ISSUE TITLE
Environment variables with PowerDNS Provider do not work

### ISSUE THREAD

**Issue by fabiorauber** [AnalogJ/lexicon#144]
I'm trying to use the following environment variables to configure the PowerDNS provider:
```
LEXICON_POWERDNS_TOKEN=a_valid_token
LEXICON_POWERDNS_PDNS_SERVER=https://a.valid.powerdns.server.com
```

But running "_lexicon powerdns list domain.com TXT_" gives:
```
Arguments: Namespace(action='list', auth_token=None, content=None, delegated=None, domain='domain.com', identifier=None, name=None, pdns_server=None, pdns_server_id=None, priority=None, provider_name='powerdns', ttl=None, type='TXT')
Traceback (most recent call last):
  File "/usr/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==2.1.10', 'console_scripts', 'lexicon')()
  File "/usr/lib/python3.5/site-packages/lexicon/__main__.py", line 68, in main
    client = Client(parsed_args.__dict__)
  File "/usr/lib/python3.5/site-packages/lexicon/client.py", line 34, in __init__
    self.provider = provider_class(self.options)
  File "/usr/lib/python3.5/site-packages/lexicon/providers/powerdns.py", line 49, in __init__
    if self.api_endpoint.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

Running with the switch works fine:

```
lexicon powerdns list domain.com TXT --auth-token a_valid_token --pdns-server https://a.valid.powerdns.server.com
```

Am I doing anything wrong?

**Comment by AnalogJ** [comment]
Only auth parameters can be passed via environmental variables.
You can use `LEXICON_POWERDNS_TOKEN=a_valid_token` but your command should include `pdns-server`:

`lexicon powerdns list domain.com TXT --pdns-server https://a.valid.powerdns.server.com`

**Comment by fabiorauber** [comment]
Humm, that explains it. Do you think it would be useful for everyone to have this feature?

**Comment by AnalogJ** [comment]
It could be useful, but it would definitely require a re-write of the options parser. The idea is that secrets can be passed via environmental variables, while all other options can be passed on teh commandline. 

If you still wanted to specify your server name via env variable, you could do it like this:

`lexicon powerdns list domain.com TXT --pdns-server $PDNS_SERVER_URL`
