### ISSUE TITLE
What is the supposed way to install `babel`

### ISSUE THREAD

**Issue by jokester** [AnalogJ/lexicon#150]
I found that when I `pip install dns-lexicon`, `babel` does not get installed as a dependency. Is it supposed to be installed explicitly?

This caused some downstream consumer to fail, like in [this docker image](https://github.com/adferrand/docker-letsencrypt-dns).

**Comment by AnalogJ** [comment]
Hey @jokester 
Some providers require [additional packages](https://github.com/AnalogJ/lexicon/blob/master/setup.py#L87-L92) to work correctly. 

The [setup section](https://github.com/AnalogJ/lexicon#setup) gives an example of how to install them

```
pip install dns-lexicon dns-lexicon[route53]
```

That Dockerfile will need to be updated to install either all the optional dependencies by 
- running `pip install -r requirements.txt`
- or looping though the entries in `setup.py`

I hope that helps!

**Comment by jokester** [comment]
@AnalogJ Thanks for your quick answer (python dependencies is definitely mysterious to me). I'm going to PR there. 👍
