### ISSUE TITLE
nsone  -- list index out of range.

### ISSUE THREAD

**Issue by init-js** [AnalogJ/lexicon#151]
using dns-lexicon 2.1.11

I'm getting a list index out of range in the process of cleaning up acme/certbot TXT records on nsone.

```
/opt/certbot # lexicon nsone list sitelabs.io TXT --auth-token MYTOKEN
Arguments: Namespace(action='list', auth_token='MYTOKEN', content=None, delegated=None, domain='sitelabs.io', identifier=None, name=None, priority=None, provider_name='nsone', ttl=None, type='TXT')
Starting new HTTPS connection (1): api.nsone.net
https://api.nsone.net:443 "GET /v1/zones/sitelabs.io HTTP/1.1" 200 None
Starting new HTTPS connection (1): api.nsone.net
https://api.nsone.net:443 "GET /v1/zones/sitelabs.io HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==2.1.11', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/site-packages/lexicon/__main__.py", line 69, in main
    client.execute()
  File "/usr/local/lib/python2.7/site-packages/lexicon/client.py", line 44, in execute
    return self.provider.list_records(self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/local/lib/python2.7/site-packages/lexicon/providers/nsone.py", line 68, in list_records
    'content': record['short_answers'][0],
IndexError: list index out of range
```

The current record list for TXT records is (from the nsone panel):

![image](https://user-images.githubusercontent.com/1110751/33194468-0735c3b6-d085-11e7-91a2-f99b7b658957.png)

Has there been an nsone response format change?

**Comment by init-js** [comment]
Adding more info.

Dumping the record information before processing reveals that the problem is with nsone "linked" records.

```
...
{u'domain': u'sitelabs.io', u'short_answers': [u'dns1.p03.nsone.net', u'dns2.p03.nsone.net', u'dns3.p03.nsone.net', u'dns4.p03.nsone.net'], u'ttl': 3600, u'tier': 1, u'type': u'NS', u'id': u'599ce1d3a632f60001a95c76'}
{u'domain': u'sitelabs.io', u'short_answers': [u'v=spf1 mx -all'], u'link': None, u'ttl': 3600, u'tier': 1, u'type': u'TXT', u'id': u'59a479fda632f6000199e90b'}
{u'domain': u'www.sitelabs.io', u'short_answers': [], u'link': u'sitelabs.ca', u'ttl': 3600, u'tier': 1.0, u'type': u'A', u'id': u'59ac55a1a632f60001df4361'}
...
```
In this case. www.sitelabs.io is linked to sitelabs.ca

I'll let you decide whether you should recurse (and fetch the linked record), just fake a CNAME, or just skip, but that's a corner case that needs special treatment in any case.

**Comment by AnalogJ** [comment]
Hmm, I'm not really familiar with NSOne's link feature. Is this something you can open a PR to fix?

**Comment by init-js** [comment]
It's a way for nsone users to de-duplicate dns record information, without requiring dns clients to pay the price of a CNAME. It effectively makes a record a symbolic link to another one on their database.

https://ns1.com/articles/cname-alias-and-linked-records

I'm happy to patch it, but should the "linked" status be exposed in the lexicon output? Fetching details for a linked record would require another dnsone API lookup. Is there another provider which has a similar feature, and from which the behaviour could be replicated?

**Comment by AnalogJ** [comment]
Looking at what you said, I think it would make sense to fake a CNAME record for it, with another API lookup. 

I don't think there's an example of another provider doing anything similar, unfortunately.

**Comment by init-js** [comment]
Created PR https://github.com/AnalogJ/lexicon/pull/157 .

**Comment by AnalogJ** [comment]
This should be fixed now. Closing.
