### ISSUE TITLE
Zoneedit support

### ISSUE THREAD

**Issue by maciekish** [AnalogJ/lexicon#158]
Any chance for Zoneedit support please? Seems like there is an API http://forum.zoneedit.com/index.php?threads/dns-update-api.419/

**Comment by AnalogJ** [comment]
Hey @maciekish 
I'd love to add it. Are you willing to contribute/open a PR?

**Comment by AnalogJ** [comment]
I've also added it the README.md.

**Comment by chewi** [comment]
I'm not too sure but I get the impression that this API has gone away since ZoneEdit changed hands. People have been asking for it more recently and they have said it's not available yet.

**Comment by AnalogJ** [comment]
@chewi Thanks for the update. Once they release their API, I'm more than happy to add it to lexicon.

-Jason
