### ISSUE TITLE
importlib-metadata package not needed

### ISSUE THREAD

**Issue by catdevnull** [AnalogJ/lexicon#1604]
hey, importlib-metadata the package isn't used, the one packaged with the stdlib is. it should be removed from the dependencies.

alpine linux patched over it: https://gitlab.alpinelinux.org/alpine/aports/-/commit/5bfc9d83f5ac1160017a7e79ac565c8314c4d24e

see https://github.com/python/importlib_metadata#compatibility

**Comment by nekopsykose** [comment]
actual patch would be

```diff
-importlib-metadata = ">=4"
+importlib-metadata = { version = ">=4", python = "<3.10" }
```

(or whatever the version was)

**Comment by adferrand** [comment]
This is done. Thanks !
