### ISSUE TITLE
Namecheap support not optional

### ISSUE THREAD

**Issue by mamash** [AnalogJ/lexicon#163]
Unlike route53 or softlayer and unlike what setup.py suggests, the namecheap provider is not optional in 2.1.17.

**Comment by AnalogJ** [comment]
Thanks for the heads-up @mamash 
I've released a new version of lexicon with a fix for that issue.

**Comment by lkraav** [comment]
Am I missing what "optional" means in lexicon context? Does it mean "not required for lexicon install, but if I want to use Namecheap, it is mandatory to install lexicon[namecheap] helper library"?

**Comment by adferrand** [comment]
It is exactly that!

**Comment by lkraav** [comment]
I had a hard time reaching this conclusion. Lexicon having namecheap.py installed, and 94210ad comment makes it look like it's more of a convenience, an alternative "upgraded" API implementation, "optional", don't really have to install it. Something like "You MUST install your specific providers dependencies." somewhere would've been helpful.

**Comment by adferrand** [comment]
In fact, the inline help for this provider dynamically adds a warning message saying this when the dependencies are missing.

I am also planning to deliver soon a complete online documentation that will include these instructions for relevant providers.

And on the long term I would simply not depend on these optional deps, and use only the lexicon core deps.

**Comment by lkraav** [comment]
> In fact, the inline help for this provider dynamically adds a warning message saying this when the dependencies are missing.

Yes, my feedback also encompasses having seen that message. It still seemed "optional". Hence my all-caps "MUST" suggestion to drive the point home in the inline warning message. Of course, maybe I'm in the measurement error % size thick skull pool and everyone else gets it.

Your long term roadmap sounds good.
