### ISSUE TITLE
docs: Certbot documentation

### ISSUE THREAD

**Issue by alexzorin** [AnalogJ/lexicon#170]
Hi, love the idea and execution of your project.

At the moment your README primarily only refers to dehydrated as an ACME client.

IME the majority of users of Let's Encrypt end up seeing and trying Certbot before any other client. I think it would be tremendously helpful to both projects if lexicon could include some words on how to use it with Certbot.

[I've written a guide of sorts here](https://id-rsa.pub/post/certbot-auto-dns-validation-with-lexicon/) but it might be even better to just include an example Certboot hook in the README or GitHub wiki or whatever.

Curious to hear what sounds good to the maintainers.

**Comment by AnalogJ** [comment]
Hey @alexzorin 
Thats a great idea actually.

There's an example hook file for `dehydrated` in the [examples/dehydrated.default.sh](https://github.com/AnalogJ/lexicon/blob/master/examples/dehydrated.default.sh), and I think that adding one for `certbot` there would make a lot of sense, especially if its paired with a docker image. 

Is that something you could open a PR for?

**Comment by alexzorin** [comment]
Yes, I'd be happy to contribute an example Certbot hook when I get the chance.

At the moment I am thinking about how best to direct users with configuring the flags for any Lexicon provider (presently, listening the providers as comments in the hook and pointing them to e.g. `lexicon cloudflare -h`). 

Maybe a further/future task could be populating the README or Wiki with per-provider instructions/screenshots on figuring out the provider flags.
