### ISSUE TITLE
Wrong requests requirement

### ISSUE THREAD

**Issue by jpiron** [AnalogJ/lexicon#1765]
Hi,
Since the following commit [e4db692cda2e3c677d7f61ee3d89e015a3ea5807](https://github.com/AnalogJ/lexicon/commit/e4db692cda2e3c677d7f61ee3d89e015a3ea5807), \
the `requests` requirement in `pyproject.toml` should be `requests = ">=2.27.0"` as the `requests.exceptions.JSONDecodeError` class has been added in this version (SEE: https://github.com/psf/requests/releases/tag/v2.27.0)

**Comment by adferrand** [comment]
This is quite relevant given the current code, but I would like to keep the widest possible compatibility with `requests` versions.

So instead I will import explicitly `JSONDecodeError` directly from `simplejson` or `json`.

Thanks !

**Comment by adferrand** [comment]
Version `3.16.1` is on its way.
