### ISSUE TITLE
lexicon with dnspod login fails

### ISSUE THREAD

**Issue by sunzhongmou** [AnalogJ/lexicon#178]
lexicon $PROVIDER --auth-username="${DNS_USERNAME}" --auth-token="${DNS_TOKEN}"  create ${DOMAIN} TXT --name="_acme-challenge.${DOMAIN}." --content="${TOKEN_VALUE}"

And the logs we got:
rocessing twer.vip
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting authorization for twer.vip...
 + 1 pending challenge(s)
 + Deploying challenge tokens...
deploy_challenge called: twer.vip, M1czG8c1Qs_1L5qBznCoIUfRZ0jT9ealak0puHUegBo, M4Ljkmaq0oVXNe7Y0dNVs_QAAkWa0bXhciMe4l4gs8k
Arguments: Namespace(action='create', auth_token='113588,xxxxx$c5427facc2a89a4763878981fcb16992', auth_username='xxx@gmail.com', content='M4Ljkmaq0oVXNe7Y0dNVs_QAAkWa0bXhciMe4l4gs8k', delegated=None, domain='twer.vip', identifier=None, log_level='DEBUG', name='_acme-challenge.twer.vip.', priority=None, provider_name='dnspod', ttl=None, type='TXT')

We got exception at last:

Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/lexicon/__main__.py", line 72, in main
    client.execute()
  File "/usr/local/lib/python2.7/site-packages/lexicon/client.py", line 38, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python2.7/site-packages/lexicon/providers/dnspod.py", line 30, in authenticate
    raise Exception(payload['status']['message'])
Exception: Missing user token, login failed

And after we step into the code for dnspod, the root api url is set to "https://dnsapi.cn", but when we check the DNSPOD API doc, which shows url like "https://api.dnspod.com/Domain.Create", but after we changed the root url to it, the error still there with same error message.

**Comment by AnalogJ** [comment]
pinging @zjs , as he worked on the dnspod provider.

From what I'm seeing, a valid auth_token should work, though the endpoint domains look interesting. Let me take a longer look and see if I can figure it out. 
Hopefully @zjs has a better understanding of what could be going wrong here.

**Comment by zjs** [comment]
I don't think I ever modified the dnspod provider except to tweak some logging, unfortunately. It was one of the providers I tried to integrate with certbot (certbot/certbot#4590), but I had a hard time navigating their documentation and never found the time to get back to that project.

**Comment by AnalogJ** [comment]
hey @sunzhongmou 
Are you still having this issue?

**Comment by AnalogJ** [comment]
Hey @sunzhongmou is this still a problem for you?

**Comment by AnalogJ** [comment]
Closing.
