### ISSUE TITLE
(Request) FreeDNS provider support

### ISSUE THREAD

**Issue by lazerhawk** [AnalogJ/lexicon#187]
FreeDNS doesn't have an API per se, but uses a brutally simple web interface that hasn't changed in years.

**Comment by AnalogJ** [comment]
Hey @lazerhawk 
I think I looked at this earlier, but from what I recall FreeDNS doesn't support all the standard DNS actions that lexicon expects. 

In any case, I've added it to the list of providers we'd like to support. Hopefully someone will have time to dive into the docs and open a PR for it. Unfortunately I won't have time to start adding providers myself for a while.
