### ISSUE TITLE
Problem with update_record api

### ISSUE THREAD

**Issue by trinopoty** [AnalogJ/lexicon#200]
This is not an issue per se. Rather, a design flaw in lexicon.
This issue is not present in providers that have some form of concrete record identifier.
I'll try to explain it.
Almost all providers provide support for multiple records with the same name and type. For example, I can have a record named "test" of type "A" and value "1.1.1.1" and "2.2.2.2". In zonefile, it would look something like this:
```
test 3600 IN A 1.1.1.1
test 3600 IN A 2.2.2.2
```
On providers that have record identifier implemented, I can target either one of these and change it. For instance, I can change "2.2.2.2" to "3.3.3.3" and it would look like this:
```
test 3600 IN A 1.1.1.1
test 3600 IN A 3.3.3.3
```

The problem begins when a provider does not implement record ids. Without a record id, there is currently no way to target only one of the records.
The current signature of `update_record` is `update_record(identifier, type, name, content)`.
The parameter `content` is the new content the needs to be placed there. There is no option to specify the existing content. This effectively means that it's impossible to update records like these without a concrete identifier implemented by the provider.
Under the current implementation of most lexicon providers, the first record returned by the provider will be updated. Under most cases, this means that calling `update_record(None, 'A', 'test', '3.3.3.3')` will update `1.1.1.1` to `3.3.3.3`. But this is unpredictable because if the provider were to reorder the result in a list call, `2.2.2.2` could get updated instead.

I understand that this problem is difficult to fix in the current major version of the lexicon with so many other stuff depending on it but this problem should be fixed asap.

**Comment by AnalogJ** [comment]
Yeah this is definitely an issue. 
I'm working on extending the test suite further to support updates of records in record sets. I'll link that PR to this issue when I get it started.

**Comment by adferrand** [comment]
For godaddy, I solved the issue by implementing a pseudo identifier, which is a hash calculated on the existing record data. It is available only until next modification, but at least you can target one record.

But it is rather specific to each provider which does not have an identifier.

**Comment by ags-slc** [comment]
The `localzone` provider also solves this in the manner described by @adferrand, in case anyone would like to see an example. #316

**Comment by adferrand** [comment]
Test suite check now updates of records in record sets. It just needs to be added progressively to all existing providers in Lexicon once we have the occasion to do so.
