### ISSUE TITLE
Tests should support an 'offline only' mode, and fail if a recording is not present.

### ISSUE THREAD

**Issue by jvanasco** [AnalogJ/lexicon#209]
The way tests are currently implemented, if a recording is not present, they will hit the real API on the internet.

The test suite should be adapted to default into immediately failing those tests.

Why?

If a new test is created upstream and the cassettes are not updated, running the tests (or tox) locally will attempt to connect to the real API from a user or the CI system's network.  Many of these APIs have ratelimiting, honeypotting and tarpitting/teergrubing enabled.

For example, The GoDaddy API seems to have a tarpit that slows the connection down and delays a response when bad credentials are submitted (as a public service to tie up bot attacks).  The new tests will not only fail against their API, but each test will take several minutes to run.  What should be a 2-3 minute total test run will take upwards of 11 minutes.  This could potentially also have the effect of banning the Api client's ip address/range.

**Comment by AnalogJ** [comment]
This is a good idea. VCR.py supports the mode you're talking about: [`none`](https://vcrpy.readthedocs.io/en/latest/usage.html#none)

When I have some time, I'll try to dynamically set the record_mode depending on if the `CI` environmental variable is set. 

https://github.com/AnalogJ/lexicon/blob/master/tests/providers/integration_tests.py#L14

**Comment by jvanasco** [comment]
I think it would make sense to have this disable the live tests by default, then opt-them-in via a LEXICON_LIVE_TESTS variable.

Under the current design there's no reason why the tests should run against the live APIs unless the developer of a provider is running it.

**Comment by AnalogJ** [comment]
Yeah, you have a point. I think I was just being a bit selfish, I find my self deleting and re-creating recordings more than regular users/developers would. 

I'll take a look at changing the default to `none`

**Comment by AnalogJ** [comment]
closed by #242.
