### ISSUE TITLE
Q: Use lexicon as a fallback solution for DDNS?

### ISSUE THREAD

**Issue by white-rabbit07** [AnalogJ/lexicon#216]
Hi. Just a question ... is it possible to use lexicon as a solution for this scenario: 
We use a vServer with a CNAME-record that points to a dynDNS-service. This service failed last days as the domain was suddenly down. So none of our services could be reached any more (especially via LDAPS). 
Is it possible to install a fallback DDNS-record using lexicon? Did anybody try this?
Idea: DynDNS1 fails --> lexicon changes the CNAME-record to DynDNS2.

**Comment by AnalogJ** [comment]
Unfortunately there's no provider for `DynDNS` in lexicon yet.

Once a provider has been added, and you have a method of being notified when a `DynDNS` record fails (via a webhook, or just a polling script), then yeah this should be possible with lexicon.

Are you interested in submitting a provider for `DynDNS`?

**Comment by white-rabbit07** [comment]
Interested: yes -- 
my coding: a disaster :(
But to check if a DDNS-Service works properly it would be enough to curl a file "check.html" with a keyword like "up" in it, right?

**Comment by AnalogJ** [comment]
Hey @white-rabbit07 
I'm going to close this issue for now, as it doesn't seem like theres any issue with lexicon here. 

If you do end up writing a DDNS provider and run into any problems, feel free to open another issue.
