### ISSUE TITLE
Update of bind

### ISSUE THREAD

**Issue by mekanix** [AnalogJ/lexicon#217]
If one hosts it's own DNS server, is it possible to use lexicon? If not, what would be the proper way to support it, given one only needs rndc and key to update a zone? Thank you!

**Comment by AnalogJ** [comment]
Hey @mekanix , @alexzorin  is correct, we don't have a RFC2136 provider yet.

Are you interested in opening a PR?

**Comment by alexzorin** [comment]
Could the testing framework support a non-HTTP provider like RFC2136? It seems to me to be assuming of HTTP (due to the use of VCR).

**Comment by mekanix** [comment]
@AnalogJ I'm interested, I just don't have any public zone. I did use rndc extensively, so I know how it behaves from sys admin perspective. I'll try to create a bind with a public zone and test it.

**Comment by AnalogJ** [comment]
Thats an interesting point @alexzorin. 
I think its useful to have a RFC2136 provider but we'd probably have to disable the test suite & recordings. 

@mekanix I'm willing to help anyway I can.

**Comment by mekanix** [comment]
So, I played with RNDC for the past few days, but I would really love to get an advice which Python lib to use for the task. Can you recommend some, given you're dealing with py+dns a lot longer than I do? Thanx!

PS. I've got bind in FreeBSD jail so I can play with it.

**Comment by alexzorin** [comment]
`dnspython` is what you want. I spent 5 minutes working on it a couple of weeks ago but abandoned my efforts because I have no time for it, but I did identify some ... complications.

My (non-functional) stub is:

```python
import logging
import dns.update

from .base import Provider as BaseProvider

logger = logging.getLogger(__name__)

def ProviderParser(subparser):
    subparser.description = '''
        The RFC2136 provider requires the RFC2136 server, TSIG key name and TSIG key secret.'''
    subparser.add_argument('--auth-username', help='The TSIG Key Name')
    subparser.add_argument('--auth-token', help='The TSIG Key Secret')
    subparser.add_argument('--auth-server', help='The RFC2136 server')

class Provider(BaseProvider):

    def __init__(self, options, engine_overrides=None):
        super(Provider, self).__init__(options, engine_overrides)

        if not self.options['auth_username']:
            raise Exception('Error, TSIG Key Name is not defined')
        if not self.options['auth_token']:
            raise Exception('Error, TSIG Key Secret is not defined')
        if not self.options['auth_server']:
            raise Exception('Error, RFC2136 Server is not defined')

    def authenticate(self):
        self.keyring = dns.tsigkeyring.from_text({
            self.options['auth_username']: self.options['auth_token']
        })
    
    def create_record(self, type, name, content):
        ttl = self.options['ttl']
        if not ttl:
            ttl = 21600

        update = dns.update.Update(self.options['domain'], keyring=self.keyring)
        update.add(self._relative_name(name), ttl, content)

        response = dns.query.tcp(update, self.options['auth_server'])
        logger.debug('create_record: %s', response)

        return True

    def list_records(self, type=None, name=None, content=None):
        records = []

        logger.debug('list_records: %s', records)
        return records

    def update_record(self, identifier, type=None, name=None, content=None):
        ttl = self.options['ttl']
        if not ttl:
            ttl = 21600

        update = dns.update.Update(self.options['domain'], keyring=self.keyring)
        return True

    def delete_record(self, identifier=None, type=None, name=None, content=None):
        return True
```

and you can take a look at [Certbot's RFC2136 implementation](https://github.com/certbot/certbot/blob/master/certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136.py) for an example of that library is meant to be used.

**Comment by mekanix** [comment]
All right! This is easier than I anticipated. I'll be working on this in the following days. Thank you!

**Comment by AnalogJ** [comment]
Hey @mekanix 
Anything I can do to help here?

I'll just close this issue for now until your PR is opened.

**Comment by marksteward** [comment]
Did this PR ever get opened?

**Comment by commonism** [comment]
The provider is called ddns.
If you want to use it …, in a multi domain zone environment, it's quite a challenge to get the provider working.

For rfc2136/ddns lexicons resolve_zone_name should use the TSIG authenticated resolver which is to be used to write the records. 
Additionally lexicon does not add the zones domain to the providers configuration context, but writes the zone domain to the global scope.
Therefore the provider does not have a zone to write to and fails.

As it was to much of a headache to get this working and I was looking for a robust asyncio solution, I ended up doing rfc2136 myself.

https://github.com/noahkw/acmetk/blob/master/acmetk/plugins/lexicon_solver.py
https://github.com/noahkw/acmetk/blob/master/acmetk/plugins/rfc2136_solver.py

**Comment by marksteward** [comment]
In the end I realised certbot's rfc2136 support doesn't rely on lexicon, so I used that directly instead of the docker image I'd been pointed at.

**Comment by commonism** [comment]
For use in certbot, it's worth limiting the scope of the TSIG credentials as outlined here:
https://certbot-dns-rfc2136.readthedocs.io/en/stable/#id5

**Comment by marksteward** [comment]
Yeah, that's what I ended up with. Thanks!
