### ISSUE TITLE
Error 500 while using Cloudflare

### ISSUE THREAD

**Issue by Techman-** [AnalogJ/lexicon#221]
Hello,

I have encountered a mysterious HTTP 500 error from Cloudflare on one of my servers, and it seems isolated to specifically that one.

[I posted the console output in a pastebin.](https://pastebin.com/TtPrQn4a) At first glance, it looks like my auth username nor token is shown in the debug output, but I have LEXICON_CLOUDFLARE_USERNAME and LEXICON_CLOUDFLARE_TOKEN set using the instructions in the README.

**Comment by pmkane** [comment]
Techman-:

I'd expect that behavior if you had not exported the environment variables before running dehydrated.

Can you confirm that you have done:

  export LEXICON_CLOUDFLARE_USERNAME=username
  export LEXICON_CLOUDFLARE_TOKEN=token

where "username" and "password" are your username and password, of course, before running dehydrated?

**Comment by AnalogJ** [comment]
Hey @Techman- 

Yeah I think @pmkane  is correct, if your calling `lexicon` via `dehydrated`, you'll need to ensure that the env variables are exported.

I've updated the readme to make that clearer.

Can you confirm that exporting the variables fixed your issue?

**Comment by Techman-** [comment]
Yes, this solved the issue. However, I've exported my environment variables before on my other servers and it has worked fine. I'm not sure if this was a one-off thing or not, but if it happens again I'll be sure to report back.
