### ISSUE TITLE
Problems executing lexicon

### ISSUE THREAD

**Issue by alexbruy** [AnalogJ/lexicon#225]
I'm trying to use lexicon 2.2.1 in the dehydrated hook to update DNS records. However hook always fails with strange error
```
usage: lexicon vultr [-h] [--name NAME] [--content CONTENT] [--ttl TTL]
                     [--priority PRIORITY] [--identifier IDENTIFIER]
                     [--log_level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}]
                     [--auth-token AUTH_TOKEN]
                     {create,list,update,delete} domain
                     {A,AAAA,CNAME,MX,NS,SOA,TXT,SRV,LOC}
lexicon vultr: error: the following arguments are required: type
```
But if I execute same command as written in the hook manually everything works as expected, record updated.

Here is command I use

```
lexicon $PROVIDER --auth-token $LEXICON_TOKEN create ${TLD_DOMAIN} TXT --name="_acme-challenge.${TLD_DOMAIN}" --content="${TOKEN_VALUE}"
```
Any ideas what can be wrong?

**Comment by AnalogJ** [comment]
If I had to guess, it sounds like lexicon thinks that `TLD_DOMAIN` is empty, so all the arguments are shifted over by one. 

Can you verify that `TLD_DOMAIN` is populated when you run lexicon via the hook?

**Comment by alexbruy** [comment]
@AnalogJ, thanks for the hint, it was issue with shifted arguments. I think ticket can be closed.

Do think it is worth to handle such situation in a more informative way, e.g. show custom error message?

**Comment by AnalogJ** [comment]
not really, its kind of hard to automatically validate all possible input combinations. However with the --debug flag enabled, lexicon will print a list of the parsed parameters.
