### ISSUE TITLE
digitalocean domain name trimmed to 2 parts

### ISSUE THREAD

**Issue by jmaasing** [AnalogJ/lexicon#227]
I'm using lexicon --version
lexicon 2.2.2

Installed by `pip install` on Debian 9.

I'm trying to list the domain 'darkstar.zoom.nu' using the digitalocean provider. However I get the following error:

`lexicon digitalocean list darkstar.zoom.nu A`
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.digitalocean.com/v2/domains/zoom.nu` 

Which isn't the correct domain. If I use curl to get the domain information directly from digitalocean it responds correctly:

`curl -X GET "https://api.digitalocean.com/v2/domains/darkstar.zoom.nu" -H "Authorization: Bearer $TOKEN"
{"domain":{"name":"darkstar.zoom.nu","ttl":1800,"zone_file":"$ORIGIN darkstar.zoom.nu .... `

**Comment by AnalogJ** [comment]
Hey @jmaasing 

Thats a subdomain, not a domain. `zoom.nu` is the domain, and as part of lexicon's authorization process it tries to verify that the domain is registered with the provider before trying to generate a certificate for a subdomain.

**Comment by adferrand** [comment]
I continue my tour with delegated option (two others issues related to this).

For @jmaasing, "darkstar.zoom.nu" is really the domain, in fact a delegated domain from main domain "zoom.nu", as the direct API test with curl shows it.

But lexicon does not know that, and will automatically trim given domain to "zoom.nu".

@jmaasing, you need to use the "delegated" option set to "darkstar" to ensure that lexicon use "darkstar.zoom.nu" as domain.

**Comment by jmaasing** [comment]
Thanks, but I wrote my own dehydrated hook file to talk to Digital Oceans API so I'll close this issue.
