### ISSUE TITLE
Capabilities system to dynamically enable/disable tests?

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/lexicon#230]
Provider API's can vary significantly. 

While the goal of `lexicon` is to provide a provider agnostic CLI/library for manipulating records, the fact that we have a single integration test suite is causing issues.

Enabling & disabling individual tests is one option, but it might be better to come up with a list of "capabilities" for each provider, and disable tagged tests that way. 

potential "capabilities"

- unique record identifiers
- set TTL support
- delegation (`x.y.z.example.com`)

**Comment by adferrand** [comment]
That has been done.
