### ISSUE TITLE
Challenge TXT Records placed in wrong domain

### ISSUE THREAD

**Issue by IainDouglas** [AnalogJ/lexicon#233]
CentOS 7.5
Lexicon 2.2.3
Provider dnsmadeeasy

I am trying to move from dehydrated + another plugin to dehydrated + lexicon for obtaining certificates. 

I have domain example.com with subdomain zy.example.com at DNSMadeEasy. 
I can obtain certificates for hosts in example.com using lexicon without issue. However certificates for hosts in zy.example.com fail the challenge e.g. xyz.zy.example.com fails.

Using the DNSMadeEasy control panel I see that the TXT record _acme-challenge.xyz.zy gets created in the example.com domain. However looking up TXT _acme-challenge.xyz.zy.example.com fails with NXDOMAIN. 

If I go back to the previous plugin, I can see that it creates the challenge TXT records in the zy.example.com (sub)domain e.g.  _acme-challenge.xyz gets put in zy.example.com and that these are readily resolved.

I'm not sure if this is a bug or if I missed something in the documentation. Is there are way to resolve this ?

**Comment by AnalogJ** [comment]
hmm. this should be correctly handled by lexicon. I think we even have a test for it. let me confirm.

**Comment by adferrand** [comment]
Looks really similar to #243. 

FQDN specified is xyz.zy.example.com, and lexicon interpret the domain to be example.com and subdomain to be xyz.zy. The option "delegated" should help by setting it to "zy". With this, lexicon will interpret correctly the domain to be "zy.example.com".

**Comment by AnalogJ** [comment]
This should be correctly handled by delegated domains. 

I'm going to close this for now, but feel free to reopen if its still a problem.

**Comment by IainDouglas** [comment]
Hi, I just had an opportunity to try this again and the problem remains. 
CentOS 7.5
Lexicon 2.7.0
Provider dnsmadeeasy.
