### ISSUE TITLE
Add a test suite to ensure that lexicon works when called as a library. 

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/lexicon#248]

**Comment by adferrand** [comment]
Is it really needed? I mean, in the existing integration tests, lexicon is already invoked as a library, and there is no real difference between making an import in a test class or in a normal class.

What would be relevant also, would be to fake a pip install and invoke lexicon as an executable through os.system, to ensure that a bash script can use lexicon.

**Comment by AnalogJ** [comment]
It doesn't need to be a massive test suite, just something simple to ensure that when lexicon is called as a library it loads and executes as expected. 

You're right, the core logic and provider interactions are tested as if they are called via a library already, so it would only need to test the `includes` and provider initialization works correctly. 

Ah, a fake pip install could be nice, but I'm not sure if tox supports that, and I dont want to add a test dependency on `docker`

**Comment by adferrand** [comment]
This issue could be closed.
