### ISSUE TITLE
godaddy: hidden dependency on urllib3 breaks Lexicon

### ISSUE THREAD

**Issue by alexzorin** [AnalogJ/lexicon#249]
#241 snuck in an undeclared dependency onto `urllib3`.

I found out today when trying to use an unrelated provider (Route53) and Lexicon immediately crashed.

```
File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/lexicon/providers/godaddy.py", line 8, in <module>
  from urllib3.util.retry import Retry
ImportError: No module named urllib3.util.retry
```

urllib3 should be avoided or declared for `godaddy` in `setup.py`:

https://github.com/AnalogJ/lexicon/blob/5f905a4707249757d10ad8afbb55aae79a09aa1a/setup.py#L88-L94

cc @adferrand

**Comment by alexzorin** [comment]
Seems that this is less straightforward than I thought.

urllib3 appears to be a transitive dependency of dns-lexicon via requests, but urllib3 not being installed can be reproduced by installing certbot-auto then,

    cd /opt/eff.org/certbot/venv
    source bin/activate
    pip install dns-lexicon dns-lexicon[route53]
    pip list | grep requests
    pip list | grep urllib3

You will see that `requests 2.12.1` is installed but `urllib3` is not.

I'm not sure what's going on. Any Python experts?

**Comment by AnalogJ** [comment]
Hey @alexzorin 

That is weird. The only provider that directly depends on `urllib3` is godaddy, but like you noticed it should be installed automatically by the `requests` dependency.

https://github.com/requests/requests/blob/991e8b76b7a9d21f698b24fa0058d3d5968721bc/setup.py#L54

I'm not quite sure how your installation in `certbot-auto` differs from normal, but I'm happy help out.
Do you have an open issue number for this on the `certbot` repo?

**Comment by adferrand** [comment]
Yep, I used urllib3 because Godaddy API is really gross. It does not accept any new request during DNS entry deployment 😑. So I need to retry the next request until it is accepted, and this kind of behavior is provided by urllib3. But as said, it is a transitive dependency of request, and I did not see any error during my development and tests.

**Comment by david-rahrer** [comment]
I am getting this same error using the script getssl along with lexicon. It only started recently on a system using Ubuntu 14.04. Lexicon and getssl are both current.

```
No handlers could be found for logger "lexicon.providers.auto"
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lexicon/cli.py", line 101, in main
    parsed_args = generate_cli_main_parser().parse_args()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/parser.py", line 60, in generate_cli_main_parser
    'lexicon.providers.' + provider)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/godaddy.py", line 9, in <module>
    from urllib3.util.retry import Retry
ImportError: No module named retry
getssl: DNS_ADD_COMMAND failed for domain mydomain.com
```
I've searched around but everything seems to be installed and up-to-date. We don't use GoDaddy, the domain is using CloudFlare. Any advice would be appreciated.
