### ISSUE TITLE
[CLI] Pretty output for list method

### ISSUE THREAD

**Issue by apognu** [AnalogJ/lexicon#251]
Is there any plans to have pretty outputs (table or at least formatted) for the ```list``` operation on the CLI?

Right now, the CLI assumes a verbosity of DEBUG level, and outputs the Python representation of the result (managed by the provider). If --log_level=ERROR is used, no output is generated, which defeats the CLI usage, in my opinion.

Is this behavior expected? Would you be open to a PR for that?

**Comment by adferrand** [comment]
Very close to #253. Definitely without the logger, there is no real output to the command line.

I also agree that default log level in cli should be higher, like WARN, and lexicon should return an output to cli.
