### ISSUE TITLE
Azure DNS provider

### ISSUE THREAD

**Issue by elyscape** [AnalogJ/lexicon#252]
It would be nice if lexicon supported [Azure DNS]. Azure DNS has [a REST API][REST] but, given that there are [numerous forms of credentials][creds] (like with AWS), it might make sense to use [the Python SDK][SDK], like in the Route 53 provider.

[Azure DNS]: https://azure.microsoft.com/en-us/services/dns/
[REST]: https://docs.microsoft.com/en-us/rest/api/dns/
[creds]: https://docs.microsoft.com/en-us/python/azure/python-sdk-azure-authenticate?view=azure-python
[SDK]: https://docs.microsoft.com/en-us/python/api/overview/azure/dns?view=azure-python

**Comment by adferrand** [comment]
About authentication, after quick review, it seems that only relevant headless authentication procedures are the two first ones (token and file), and in fact they are the same, as the file approach is just a handy way to persist all elements required to create the token.

It seems for the principle quit close to what is used with Google Cloud DNS, and I just made a PR on lexicon to implement the provider.

I would be quite interested to make a provider for Azure DNS, but I do not have an account. If you are OK with that, you could provide me an access to your instance, and maybe a dummy domain (or a way to attach a free domain to Azure, like with FreeNom) to make the devs.

**Comment by elyscape** [comment]
I can hook you up with credentials for a dummy zone, sure. Contact me via email or on Freenode and we'll make it happen.

**Comment by AnalogJ** [comment]
Hey @elyscape 
Thats a good idea, I've added Azure DNS to the README as a potential provider.

I don't personally use Azure DNS, but it seems like @adferrand is interested in working with you to write a provider, so thats great.

**Comment by adferrand** [comment]
Still interested, but I could not reach you @elyscape.

**Comment by elyscape** [comment]
Apologies; it completely slipped my mind. I'll get you the test credentials sometime this week.

**Comment by adferrand** [comment]
This has been done.
