### ISSUE TITLE
Return value for list?

### ISSUE THREAD

**Issue by bagintz** [AnalogJ/lexicon#253]
I very well might be looking at this wrong, but it appears that out of the box the "executable" that gets installed for linux can't actually get the list results as a return variable, only as a stdout debug message?

**Comment by adferrand** [comment]
You mean, despite the fact that as a library, the list_records python method returns the list?

And you would like to be able to do in bash something like :
```
lexicon list... | jq...
```

I will check that.

**Comment by bagintz** [comment]
Thank you!
