### ISSUE TITLE
logos?

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/lexicon#256]
- https://thenounproject.com/search/?q=convert&i=397964
- https://thenounproject.com/search/?q=convert&i=203712
- https://thenounproject.com/search/?q=convert&i=216627
- https://thenounproject.com/parkasever/uploads/?i=426419

**Comment by adferrand** [comment]
I like the first one, really simple, really clean.

**Comment by AnalogJ** [comment]
Yeah I liked that one too. I'll just set it in the readme for now.
