### ISSUE TITLE
[Regression on #PR-203] CloudNS authentication broken when `auth-id` supplied

### ISSUE THREAD

**Issue by rwjs** [AnalogJ/lexicon#258]
Provider CloudNS fails to authenticate when using auth-id for authentication, rather than auth-subid or auth-subuser.

Line 146 in lexicon/providers/cloudns.py  reads `if self.is_given_option(self.options['auth_id']):`. It should instead should read `if self.is_given_option('auth_id'):`.

I've inlined a patch below which fixes this. Sorry if this is more effort for you than a PR.

    --- cloudns.py
    +++ cloudns.pr203fix.py
    @@ -143,7 +143,7 @@ 
             if not self.options['auth_password']:
                 raise Exception('No valid authentication data passed, expected: auth-password')
    
    -        if self._is_given_option(self.options['auth_id']):
    +        if self._is_given_option('auth_id'):
                 return {'auth-id': self.options['auth_id'], 'auth-password': self.options['auth_password']}
             elif self._is_given_option('auth_subid'):
                 return {'sub-auth-id': self.options['auth_subid'], 'auth-password': self.options['auth_password']}

**Comment by rwjs** [comment]
Can I please get an update on this? Unlike the issues which have been updated in the meantime, **this bug breaks the whole program**.

I've already done the troubleshooting.

I've already described when it broke. 

I've already supplied the fix. 

All I need is some kind of indication that this is in progress - or anything further you might need me to do.

**Comment by AnalogJ** [comment]
Hey @rwjs 
Sorry about the delay. I haven't taken a look at new issues for a bit since I've been travelling. 
In general it's much easier to merge PR's rather than patchsets since my automation is setup for it. I'll manually create a PR for this though. 

Unfortunately I can't test this change as I don't have a CloudNS account, but maybe @ppmathis can take some time and verify it.

**Comment by ppmathis** [comment]
@AnalogJ Sure! :) Ping me once you have created the PR and I will gladly get it verified.

**Comment by AnalogJ** [comment]
Hey @ppmathis did you have a chance to take a look at #270?

**Comment by ppmathis** [comment]
Sorry for the delay. I've checked #270 and can confirm it is working just fine, however I'd suggest anyone to stick to auth-id/auth-subid authentication as its probably safer to restrict API to the appropriate LE-enabled domains/zones only.
