### ISSUE TITLE
SPF support could be confusing

### ISSUE THREAD

**Issue by txr13** [AnalogJ/lexicon#26]
I note that the SPF RR type was discontinued in RFC 7208 (see https://tools.ietf.org/html/rfc7208#section-3.1). I tried searching for my own SPF records with the SPF type, but of course they were not found (they do show up as TXT records, which they are). This could lead to confusion as to whether the command should return SPF records (which are implemented as standard TXT records) or records of the SPF RR type (which has been discontinued).

For clarity, I would suggest that lexicon drop the SPF RR type. Alternately, you could allow listing the SPF RR type (possibly with a printed message for the user that notes that SPF records implemented as TXT records will not be returned), and disallow creation of SPF RRs (since current RFC specifies that  it must be implemented by TXT record only).

**Comment by aeden** [comment]
I concur. We will likely be dropping the SPF type in DNSimple at some point in favor of just the TXT record type for SPF.

**Comment by AnalogJ** [comment]
Yeah, dropping SPF looks like a good idea, I didn't realize it was deprecated. I've never used one myself, and initially just added it because it was supported by some of the providers.
