### ISSUE TITLE
Cloudflare plugin always returns success on delete

### ISSUE THREAD

**Issue by tim-seoss** [AnalogJ/lexicon#271]
I'm not particularly sure this is a real bug, but the cloudflare delete_record seems to unconditionally return True on delete, irrespective of actual success.  If this is intentional, then at the very least 'payload' in that member function is assigned but the result remains unused.

**Comment by AnalogJ** [comment]
while it is correct that alot of providers return `True` in the function calls, that doesn't mean they are unconditionally successful. Most providers have the following line in their `_request` function:

    r.raise_for_status()  # if the request fails for any reason, throw an error.

Which means they throw an error if the response returns with a non-2XX HTTP code.
