### ISSUE TITLE
DNS Challenge, Gandi, APIv4 and required delay(s)

### ISSUE THREAD

**Issue by jelockwood** [AnalogJ/lexicon#273]
I am currently setting up and testing using certbot with lexicon and our Gandi DNS provider.

As is well known if your using the classic i.e. v4 API with Gandi you need to add a sleep 1500 command to give it time to propagate the update to the DNS record. See - https://community.letsencrypt.org/t/solved-certificate-creation-failed-using-certbot-dns-challenge-and-gandi-dns-servers/54778 as an example.

However I noticed the following -

I am trying to request a cert which has the main common name and also two subject alternative names, this means you need to request three domain txt records and challenges.

I would have expected it to work by sending the request, generating all three _acme-challenge.domain txt records, sleeping for 1500 seconds and then doing the challenge. This would mean just a single 1500 second long delay.

Instead what seems to be happening is that there is a 1500 second delay in between each record creation and challenge resulting in this case in 3 x 1500 seconds of delay i.e. 4500 seconds or 75 minutes! If someone has more subject alternative names the situation would be correspondingly worse.

Would it be possible for the logic of the program to be altered so that all the creations are done in one go as a batch, then there is a single sleep and then the challenges are done in a batch also?

(It maybe this would need to be addressed in certbot rather than lexicon, please let me know if that is the case and I will repost this issue on the certbot project page.)

**Comment by AnalogJ** [comment]
This sounds like an issue with the certbot flow. Lexicon doesn't have any delays built into it. It just interacts with DNS provider API's as requested (create, update, list, delete)

The certbot team should be able to help you out.
