### ISSUE TITLE
Add command to save and restore zone records

### ISSUE THREAD

**Issue by harobed** [AnalogJ/lexicon#277]
Hi,

I would like use **lexicon** with this workflow:

1. save all records (A, AAAA, CNAME...) with one command to a `records.txt` file
2. I edit this `records.txt` file
3. I commit it with git
4. I push this new config with **lexicon**

What do you think about this workflow?

What do you think about add two new commands to save all zone records and write all zone records?

Best regards,
Stéphane

**Comment by AnalogJ** [comment]
Hey @harobed 

adding a `dump` and `restore` function definitely sounds useful, but I think there's a couple issues with it:

- philosophically `lexicon` is designed to interact with record/recordsets as its fundamental unit. DNS is an old and well understood spec, making it fairly easy to find common functionality across all DNS providers. 
- while dump/restore sounds simple on paper, I think it'll quickly run into issues where some providers require additional data/metadata/parameters when creating zones, data that lexicon will not have.

I think it should be easy enough to write a script to wrap lexicon that can do what you need on a provider-by-provider basis.
