### ISSUE TITLE
Authentication mechanisms

### ISSUE THREAD

**Issue by lukas2511** [AnalogJ/lexicon#28]
Hey,

I think this project is very interesting, but your approach on how to manage authentication with all those different providers looks like it will sooner or later be a real pain.

Some providers use different kinds of oauth, some just an API-token, some username+password, some account+subaccount+password, etc.

If you keep the login settings part of the main script I think you'll have a list of way to many confusing options very soon.

I'd suggest moving authentication options into the provider plugins, so that when you use a provider with simple token-auth it only accepts that parameter, and with oauth maybe even provide some kind of wizard that has instructions on how to set up the tool with that certain provider.

**Comment by AnalogJ** [comment]
Good point. So far the auth types that I've specified (username/password/token/2fa-token) have worked well, but I haven't yet had to take into account a subaccount, which as you mentioned would require another flag/env variable. It would be a good idea to pass auth flags to the provider itself and have them validate and specify the required flags. 

This is going to require some refactoring, but should be fairly straightforward to implement.

**Comment by AnalogJ** [comment]
v1.1.1 has been released. It includes changes so that the providers themselves can specify the auth arguments they need. Its not as clean as I'd like, especially since ArgParse doesn't have lazy subparser loading, but it does the job. I'm going to close this for now, thanks for pointing it out.
