### ISSUE TITLE
How to filter responses in VCR.py cassettes?

### ISSUE THREAD

**Issue by shodan45** [AnalogJ/lexicon#299]
For some reason, LiquidWeb's API responses include an "X-LW-User" header which echoes the user name sent in the request, and I need to filter that out. I went down a bit of a rabbit hole into the VCR.py module, and found [this](https://vcrpy.readthedocs.io/en/latest/advanced.html#custom-response-filtering) in their docs, but I don't see how to use that in lexicon without significant refactoring.

Is there a better way to do this that I'm missing? Heck, can I just manually edit the cassette files?

**Comment by AnalogJ** [comment]
Heres an example of filtering headers:

https://github.com/AnalogJ/lexicon/blob/master/tests/providers/test_cloudflare.py#L15-L16

Let me find you an example of how to filter body content

**Comment by AnalogJ** [comment]
Hmm, doesn't seem like we have a built in method for filtering response data [(only post data)](https://github.com/AnalogJ/lexicon/blob/4999a6ec783c7c1358baefe14dee0e54d2d07bb9/tests/providers/integration_tests.py#L25-L27)

If you want to open a separate PR for that, I'd be happy to merge it. 
You'll want to mimic the way we do other filtering functions in this class: 
https://github.com/AnalogJ/lexicon/blob/4999a6ec783c7c1358baefe14dee0e54d2d07bb9/tests/providers/integration_tests.py#L25-L27

**Comment by rqelibari** [comment]
> If you want to open a separate PR for that, I'd be happy to merge it.

PR #307 (_Add _filter_response method for VCR tests_) implements this functionality.

**Comment by AnalogJ** [comment]
#307 is merged now so you should be able to do response filtering in your LiquidWeb provider @shodan45 

If you need any help, feel free to open another PR. 

Thanks again for your help @rqelibari
