### ISSUE TITLE
How to handle/mapped and list multiple ENV authentications for same provider?

### ISSUE THREAD

**Issue by bsandy999** [AnalogJ/lexicon#304]
Suppose i have **two clients** for same service provider ( e.g digitalocean). 
user1:
export LEXICON_DIGITALOCEAN_USERNAME="username1@gmail.com" 
export LEXICON_DIGITALOCEAN_TOKEN="sample_token1" 

user2:
export LEXICON_DIGITALOCEAN_USERNAME="username2@.gmail.com" 
export LEXICON_DIGITALOCEAN_TOKEN="sample_token2"

After exporting credentials for both **lexicon digitalocean list domainname TXT** command will always works with the latest value and not for previous one. Just cause for same **ENV** key name. How do i resolve above issue.  I wanted to list all the values respective with their domain names. Is it possible to show/list the result as per my use case?

**Comment by AnalogJ** [comment]
yeah, unfortunately supporting multiple accounts per provider is not something that `lexicon` supports out-of-the-box. Even looking at @adferrand 's `auto` provider, I don't think it'll do what you want.

If you would like to list records for different domains across different accounts you'll need to do it with 2 separate calls to `lexicon`
