### ISSUE TITLE
Does lexicon support update? I am trying to  update DKIM value but getting requests.exceptions.HTTPError: 404 Client Error: Not Found.

### ISSUE THREAD

**Issue by bsandy999** [AnalogJ/lexicon#323]
_I wanted to update the existing value of DKIM using a lexicon. But using lexicon update is not working for me. Can you help me with this? Below is the command I am using to update DKIM value.

**lexicon Command :-** 
<pre><code>lexicon digitalocean update sampledomain.com TXT --name='pepi._domainkey.sampledomain.com' --content='k=rsa;
p=AAAAAAAAAAAAAAAAAMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLMMExLiGRqzJkNdNIjUnLX7JL0wjbwwENDoXgJIBisIsrofLPetZM401dioNU8k/Qp6nIyi5oioyZh+1jDXoCPFa4nLGRNj3Nz785N7b76aTtHmy2wTgR2LFS/Yw5/iyzhyrWsIyINyyHs77EoCwSOQjJfhFxb6SmifLN51IIvwIDAQAB'
</code></pre>

**Below is the output getting after executing the above command.**
`Traceback (most recent call last):
  File "/usr/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==2.7.9', 'console_scripts', 'lexicon')()
  File "/usr/lib/python2.7/site-packages/lexicon/__main__.py", line 136, in main
    results = client.execute()
  File "/usr/lib/python2.7/site-packages/lexicon/client.py", line 47, in execute
    return self.provider.update_record(self.options.get('identifier'), self.options.get('type'), self.options.get('name'), self.options.get('content'))
  File "/usr/lib/python2.7/site-packages/lexicon/providers/digitalocean.py", line 94, in update_record
    payload = self._put('/domains/{0}/records/{1}'.format(self.domain_id, identifier), data)
  File "/usr/lib/python2.7/site-packages/lexicon/providers/base.py", line 79, in _put
    return self._request('PUT', url, data=data, query_params=query_params)
  File "/usr/lib/python2.7/site-packages/lexicon/providers/digitalocean.py", line 136, in _request
    r.raise_for_status()  # if the request fails for any reason, throw an error.
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found`

I have exported all required parameters and working fine with the list and create commands but not with update one.

**Comment by adferrand** [comment]
Did you tried to update the record using its identifier?

**Comment by bsandy999** [comment]
I am trying with this command 

lexicon digitalocean update sampledomain.com TXT --name='pepi._domainkey.sampledomain.com' --content='k=rsa; p=AAAAAAAAAAAAAAAAAMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDLMMExLiGRqzJkNdNIjUnLX7JL0wjbwwENDoXgJIBisIsrofLPetZM401dioNU8k/Qp6nIyi5oioyZh+1jDXoCPFa4nLGRNj3Nz785N7b76aTtHmy2wTgR2LFS/Yw5/iyzhyrWsIyINyyHs77EoCwSOQjJfhFxb6SmifLN51IIvwIDAQAB'


In which 
1. sampledomain.com (will replace with my actual domain name)
2. **pepi._domainkey**.sampledomain.com (this is my identifier)

**Comment by adferrand** [comment]
I am saying that because there is to way to update a record: by unique identifier or by matching the given type and name.

But for the latter case, there is a flaw, because several records could match a given type and name. Indeed most of the time, you can insert multiple TXT for a given name.

And if multiple matches are found, some providers will update the first match, other will not update anything. Cloudflare provider could fall in the second category.

**Comment by bsandy999** [comment]
Updating the record using its identifier is pretty simple and quick. The second approach is still not working for me using the name but for now, I will do with the identifier. 
_Thanks for the help @adferrand_
