### ISSUE TITLE
Localzone provider is breaking with the latest dnspython version

### ISSUE THREAD

**Issue by adferrand** [AnalogJ/lexicon#331]
The PR #325 pointed out that localzone provider is sudently breaking. I think it is related with dnspython, a dependency of localzone provider, for which a new version as been released two days ago (8 dec 2018). See the CI logs for #325 to get the error. 

cc @ags-slc @AnalogJ

**Comment by ags-slc** [comment]
Thanks for bringing this to my attention. I'll take a look ASAP.

**Comment by ags-slc** [comment]
An updated version of localzone (v0.9.5) has been released to address this issue. Please let me know if you have any questions or concerns. Thanks!

**Comment by adferrand** [comment]
Your welcome ^^
