### ISSUE TITLE
from urllib3.util.retry import Retry - ImportError: No module named retry

### ISSUE THREAD

**Issue by david-rahrer** [AnalogJ/lexicon#346]
I am getting this same error using the script getssl along with lexicon. It only started recently on a system using Ubuntu 14.04. Lexicon and getssl are both current.

```
No handlers could be found for logger "lexicon.providers.auto"
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lexicon/cli.py", line 101, in main
    parsed_args = generate_cli_main_parser().parse_args()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/parser.py", line 60, in generate_cli_main_parser
    'lexicon.providers.' + provider)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/godaddy.py", line 9, in <module>
    from urllib3.util.retry import Retry
ImportError: No module named retry
getssl: DNS_ADD_COMMAND failed for domain mydomain.com
```
I've searched around but everything seems to be installed and up-to-date. We don't use GoDaddy, the domain is using CloudFlare. Any advice would be appreciated.

I found something similar in a closed thread https://github.com/AnalogJ/lexicon/issues/249

**Comment by david-rahrer** [comment]
Thank you, here you go:

```
root@global:~# pip freeze
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 2]) may 
cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
apt-xapian-index==0.45
boto3==1.4.4
botocore==1.5.4
certifi==2018.11.29
cffi==1.5.2
chardet==2.0.1
colorama==0.2.5
configobj==5.0.6
cryptography==1.2.2
dns-lexicon==3.0.8
docopt==0.6.2
docutils==0.13.1
enum34==1.1.2
future==0.16.0
futures==3.0.5
html5lib==0.999
idna==2.8
iotop==0.6
ipaddress==1.0.16
jmespath==0.9.0
matplotlib==1.3.1
multiprocessing==2.6.2.1
ndg-httpsclient==0.4.0
netifaces==0.10.4
ngxtop==0.0.2
numpy==1.8.2
Pillow==2.3.0
psutil==3.4.2
pyasn1==0.1.9
pycparser==2.14
pycurl==7.19.3
pymdstat==0.4.2
pyOpenSSL==0.15.1
pyparsing==2.0.1
python-apt===0.9.3.5ubuntu3
python-dateutil==2.6.0
python-debian===0.1.21-nmu2ubuntu2
pytz==2012rc0
PyYAML==3.13
requests==2.9.1
requests-file==1.4.1
s3transfer==0.1.10
six==1.10.0
tabulate==0.7.4
tldextract==2.0.2
urllib3==1.7.1
virtualenv==15.1.0
```

**Comment by adferrand** [comment]
So I see that your version of urllib3 is very old, which make sense as you are on Ubuntu Trusty. On this version, the package `urllib3.util.retry` does not exist, and this is the root of the error. Pip do not try to update it, because it is a OS package.

I you cannot go to a more recent version of Ubuntu, then I advise you to install a Python virtual environment, and install Lexicon inside it. Then you will get the latest version of urllib3 in it, that will make Lexicon work.

**Comment by david-rahrer** [comment]
Thanks again for your quick help. Is there a tutorial on installing Lexicon in a Python virtual environment? I'm not experienced with this. The only thing I found [was this](https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md) but it seems geared to development.

**Comment by adferrand** [comment]
Hello! I think that the best documentation so far is the official one: https://packaging.python.org/guides/installing-using-pip-and-virtualenv/

Indeed the one in the repository is an extended config to setup the development tools inside a Python virtual environment.

Note that once lexicon is installed inside it, you can call directly lexicon without enabling the virtual environment directly by invoking the executable at `venv/bin/lexicon`, assuming that `venv` is the folder name of your virtual environment.

**Comment by AnalogJ** [comment]
Hey @david-rahrer 
Did using a virtualenv fix your issue?
