### ISSUE TITLE
Broken CI pipeline

### ISSUE THREAD

**Issue by rembik** [AnalogJ/lexicon#349]
Error: Invalid requirement: --process-dependency-links

For more detail see pull request log, that brings up this issue. https://github.com/AnalogJ/lexicon/pull/348

**Comment by adferrand** [comment]
Yes, this deprecated option has been finally removed from pip 19.0. Hopefully I anticipated the problem with #338. The PR has been merged. You can sync your PR with master to fix the CI for you.
