### ISSUE TITLE
Does lexicon works with Go-daddy ?

### ISSUE THREAD

**Issue by bsandy999** [AnalogJ/lexicon#358]
I am trying with GoDaddy as per lexicon documentation. For digital ocean it's working fine but not with GoDaddy.
1. I tried with api-key and username
2. Tried with username and account password 
each and every time gets **Unauthorized** 
`Traceback (most recent call last):
  File "/usr/bin/lexicon", line 9, in <module>
    load_entry_point('dns-lexicon==2.7.9', 'console_scripts', 'lexicon')()
  File "/usr/lib/python2.7/site-packages/lexicon/__main__.py", line 136, in main
    results = client.execute()
  File "/usr/lib/python2.7/site-packages/lexicon/client.py", line 38, in execute
    self.provider.authenticate()
  File "/usr/lib/python2.7/site-packages/lexicon/providers/godaddy.py", line 39, in authenticate
    result = self._get('/domains/{0}'.format(domain))
  File "/usr/lib/python2.7/site-packages/lexicon/providers/base.py", line 73, in _get
    return self._request('GET', url, query_params=query_params)
  File "/usr/lib/python2.7/site-packages/lexicon/providers/godaddy.py", line 218, in _request
    result.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized
`

**Comment by adferrand** [comment]
Hello @bsandy999, normally yes it is working, as our integration tests are passing. Modifications of the Godaddy API may occur and break the provider however. 

Could you paste the exact command you issued, with the credentials values shadowed? I will try with my own credentials.

**Comment by bsandy999** [comment]
Thanks @adferrand

**Comment by adferrand** [comment]
So I assume you have followed the instructions provided in the GoDaddy API to get a key and a secret. However you are using the wrong environment variables. For Godaddy, credentials are passed through `--auth-key` and `--auth-secret`. So the environment variables are `LEXICON_GODADDY_AUTH_KEY` and `LEXICON_GODADDY_AUTH_SECRET`.

I tested on my side, everything is working.

**Comment by adferrand** [comment]
Yes. Add `dns-lexicon==2.2.3` to `certbot-dns-linode/local-oldest-requirements.txt`.

**Comment by bsandy999** [comment]
@adferrand  Thanks for the detailed information. 
 
As you have mentioned, did the same steps but still getting Unauthorized error.
Entering the correct credentials. You can find my commands below : 

> export LEXICON_GODADDY_AUTH_KEY ="sample_key"
> export LEXICON_GODADDY_AUTH_SECRET="sample_secret"

> lexicon godaddy list sampledomain.com TXT

**Error :**

Traceback (most recent call last):
 

>  File "/usr/bin/lexicon", line 9, in <module>
>     load_entry_point('dns-lexicon==2.7.9', 'console_scripts', 'lexicon')()
>   File "/usr/lib/python2.7/site-packages/lexicon/__main__.py", line 136, in main
>     results = client.execute()
>   File "/usr/lib/python2.7/site-packages/lexicon/client.py", line 38, in execute
>     self.provider.authenticate()
>   File "/usr/lib/python2.7/site-packages/lexicon/providers/godaddy.py", line 39, in authenticate
>     result = self._get('/domains/{0}'.format(domain))
>   File "/usr/lib/python2.7/site-packages/lexicon/providers/base.py", line 73, in _get
>     return self._request('GET', url, query_params=query_params)
>   File "/usr/lib/python2.7/site-packages/lexicon/providers/godaddy.py", line 218, in _request
>     result.raise_for_status()
>   File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized

Why my credetials not getting reflected, any idea?

**Comment by adferrand** [comment]
Godaddy uses two type of key/secret pairs: one type for the testing environment (OTE), another one for the production environment. Have you check that the key/secret pair you are using is for production?

**Comment by oldium** [comment]
If you do everything OK, it should work. Get the _Production_ keys to be able to modify your domain at https://developer.godaddy.com/keys, create a new API key (set some name and don't forget to select Production) and you shall see the following:

![image](https://user-images.githubusercontent.com/1260936/71830271-b5bd2e00-30a6-11ea-804b-40fa0ada46b4.png)

Those are the `LEXICON_GODADDY_AUTH_KEY` (first one) and `LEXICON_GODADDY_AUTH_SECRET` (second one) environment variables values. Note the values down and confirm the creation.

You can also test accessing your domain directly with command line to see if there is some difference to using the environment keys:

```
lexicon godaddy --auth-key YOUR_KEY --auth-secret YOUR_SECRET list my_domain.com TXT
```

If you see 401 error, your key/secret has a typo (they are case sensitive). If you see 404 error, your domain name is wrong.

**Comment by eengstrom** [comment]
Issue seems stale, and I know it works for me, up to the v3.3.23 version.  I did note one issue with FQDN including full-stop period in issue #518, but otherwise, I'd say this issue is OBE.

**Comment by adferrand** [comment]
I close this issue in favor of #518.
