### ISSUE TITLE
Add new zone? List all zones? List all records in zone? lexicon.yml config?

### ISSUE THREAD

**Issue by quinncomendant** [AnalogJ/lexicon#365]
I think there is some missing functionality in the Rackspace provider. I've read through the README.md and output from `-h`, but I can't find these features:

- List all zones (domains) in my account. I want to print a list of all domains we manage.
- List all records in a zone (domain). It seems lexicon requires specifying a record type (`A`, `TXT`, etc). Is there a way to dump the entire zone?
- Create a new zone (domain). It seems lexicon only has one `create` action, for adding records. How to add new zones?

Finally, a question about config files: I see that [config.py](https://github.com/AnalogJ/lexicon/blob/master/lexicon/config.py#L122) supports _"[…] a configuration file named '/my/path/to/lexicon.yml'"_. How do I configure the location of lexicon.yml? Is there a default location?

**Comment by AnalogJ** [comment]
The lack of zone manipulation functionality is partially due to restrictions in DNS provider API's and partially due to design decisions made when building `lexicon`

- *List all zones (domains) in my account. I want to print a list of all domains we manage.*
    - while most DNS providers have a way to list zones, CRUD functionality is inconsistent and so this was ignored. 
- *List all records in a zone (domain).*
    - this should be possible, and if not it's definitely an oversight. I'll get back to you.
- *Create a new zone (domain)*
    - This functionality is missing because it's not supported on many DNS API's. If we can confirm that some super-majority percentage (maybe 75%+) of DNS providers now allow creating/registering Domains via API, I think it would make sense to re-consider this functionality. 
    - At the same time, it's worth reiterating that the core competency of `Lexicon` is DNS record manipulation. The on-boarding and registration of new Zones varies significantly for each DNS provider, and I'm not sure if there'll ever be a standardized workflow that makes sense to do that. :(
- *How do I configure the location of lexicon.yml?*
    - @adferrand is much more familiar with the new config system. It's definitely an optional file, as most people configure `lexicon` via env variables (myself included)

**Comment by adferrand** [comment]
Concerning the location of lexicon.yml, Lexicon will search in the current directory, meaning the directory from where the shell has invoked lexicon CLI. It made me think that I forgot to make this configurable. So PR #367 ^^

**Comment by AnalogJ** [comment]
Doesn't look like there's any additional questions. Closing.
