### ISSUE TITLE
DNS Simple provider failed on creation record

### ISSUE THREAD

**Issue by cmourizard** [AnalogJ/lexicon#387]
When certbot try to add record to DNS Simple, that generates a 400 error because in this line https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/dnsimple.py#L75 the string doesn't start with "/".

That works fine until this week but doesn't work anymore. Maybe something change in the DNS Simple API return of the AccountId.

**Comment by aaronryden** [comment]
can we get this merged? it is causing breaks in this package https://pypi.org/project/certbot-dns-dnsimple/

**Comment by adferrand** [comment]
Could I have an output of the stacktrace?

**Comment by cmourizard** [comment]
Current result:
certbot certonly --noninteractive --register-unsafely-without-email --agree-tos --dns-dnsimple --dns-dnsimple-credentials .dnsimple -d mydomain.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-dnsimple, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for mydomain.com
Cleaning up challenges
Error adding TXT record: 400 Client Error: Bad Request for url: https://api.dnsimple.com/v212345/zones/mydomain.com/records

You can see that a "/" is missing just after the v2, called by https://github.com/certbot/certbot/blob/651de2dd2fea9c79caae96d039f2570518735bdc/certbot/plugins/dns_common_lexicon.py#L43

**Comment by aaronryden** [comment]
@adferrand The error is actually thrown from here:
https://github.com/aaronryden/lexicon/blob/master/lexicon/providers/dnsimple.py#L195

stating that the hostname `api.dnsimple.com/v2/` is not properly separated from . the path `/account`

You can see i have added an extra '/' at this point, instead of on line 75.

**Comment by adferrand** [comment]
I fixed the issue on 3.2.0.

**Comment by AnalogJ** [comment]
Since this is merged in v3.2.0, I'm going to close this issue. 
Feel free to respond to this issue if it needs to be re-opened.
