### ISSUE TITLE
lexicon with cloudflare does not work anymore

### ISSUE THREAD

**Issue by bottee** [AnalogJ/lexicon#392]
Hello,
trying with cloudflare worked some days ago but today I get:
```Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lexicon/cli.py", line 101, in main
    parsed_args = generate_cli_main_parser().parse_args()
  File "/usr/local/lib/python3.6/dist-packages/lexicon/parser.py", line 53, in generate_cli_main_parser
    for provider, available in discovery.find_providers().items():
  File "/usr/local/lib/python3.6/dist-packages/lexicon/discovery.py", line 25, in find_providers
    for provider in providers_list}
  File "/usr/local/lib/python3.6/dist-packages/lexicon/discovery.py", line 25, in <dictcomp>
    for provider in providers_list}
  File "/usr/local/lib/python3.6/dist-packages/lexicon/discovery.py", line 46, in _resolve_requirements
    pkg_resources.get_distribution(requirement)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 472, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range```

**Comment by somnium78** [comment]
Same here with ovh (on ubuntu 18.04)

**Comment by adferrand** [comment]
Seems there is an inconsistency here in how distributions are found by pkg_resources, depending maybe on particularities of the os. I will investigate and publish a fix today.

**Comment by bottee** [comment]
I use 'ubuntu/bionic64' version '20190403.0.0' in vagrant on macos

**Comment by adferrand** [comment]
What is your pkg_resources package version? You should be able to get it from `pip freeze`

**Comment by somnium78** [comment]
`# pip freeze
asn1crypto==0.24.0
certifi==2019.3.9
chardet==3.0.4
cryptography==2.1.4
dns-lexicon==3.2.0
enum34==1.1.6
future==0.17.1
idna==2.6
ipaddress==1.0.17
keyring==10.6.0
keyrings.alt==3.0
pycrypto==2.6.1
pygobject==3.26.1
pyOpenSSL==19.0.0
Pyro==3.16
pyxdg==0.25
PyYAML==5.1
requests==2.21.0
requests-file==1.4.3
SecretStorage==2.3.1
six==1.11.0
tldextract==2.2.1
urllib3==1.24.1`

**Comment by adferrand** [comment]
Oh sorry, could you add `--all` flag?

**Comment by bottee** [comment]
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
bcrypt==3.1.6
blinker==1.4
cached-property==1.5.1
certifi==2018.1.18
cffi==1.12.2
chardet==3.0.4
click==6.7
cloud-init==18.5
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
dns-lexicon==3.2.0
docker==3.7.2
docker-compose==1.24.0
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
future==0.17.1
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
MarkupSafe==1.0
netifaces==0.10.4
oauthlib==2.0.6
PAM==0.4.2
paramiko==2.4.2
pip==9.0.1
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
pycrypto==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
PyNaCl==1.3.0
pyOpenSSL==17.5.0
pyserial==3.4
python-apt==1.6.3+ubuntu1
python-debian==0.1.32
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
requests-file==1.4.3
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
setuptools==39.0.1
six==1.11.0
ssh-import-id==5.7
systemd-python==234
texttable==0.9.1
tldextract==2.2.1
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
websocket-client==0.56.0
wheel==0.30.0
zope.interface==4.3.2

**Comment by xueshanf** [comment]
Me too:
```
ash-4.4# lexicon route53  -h
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/lexicon/cli.py", line 101, in main
    parsed_args = generate_cli_main_parser().parse_args()
  File "/usr/local/lib/python3.7/site-packages/lexicon/parser.py", line 53, in generate_cli_main_parser
    for provider, available in discovery.find_providers().items():
  File "/usr/local/lib/python3.7/site-packages/lexicon/discovery.py", line 25, in find_providers
    for provider in providers_list}
  File "/usr/local/lib/python3.7/site-packages/lexicon/discovery.py", line 25, in <dictcomp>
    for provider in providers_list}
  File "/usr/local/lib/python3.7/site-packages/lexicon/discovery.py", line 46, in _resolve_requirements
    pkg_resources.get_distribution(requirement)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range
```

**Comment by adferrand** [comment]
Hello everyone. I could reproduce the issue, that did not occur when lexicon was installed from sources in editable mode. That is why I did not see the failure during the dev and the tests.

I made the appropriate correction, and published a new version of Lexicon, the 3.2.1, with it. I tested it and the failure disappeared.

You should be able to fix your setup by upgrading Lexicon with pip. 

Let me know if you still encountered an issue. 

I am really sorry for the disturbing.

**Comment by xueshanf** [comment]
@adferrand Yay! It did fixed the issue. 
```
bash-4.4# lexicon --version
lexicon 3.2.1
bash-4.4# lexicon route53 -h
usage: lexicon route53 [-h] [--name NAME] [--content CONTENT] [--ttl TTL]
                       [--priority PRIORITY] [--identifier IDENTIFIER]
                       [--log_level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}]
...
```
Thank you!

**Comment by bottee** [comment]
Yes, it's working again! Thank you very much for your fast response!

By the way, lexicon is a great project!

**Comment by adferrand** [comment]
Great! I am closing.
