### ISSUE TITLE
internetbs _list_records() fails when response has no records

### ISSUE THREAD

**Issue by yearski** [AnalogJ/lexicon#394]
I'm using Internet.bs: [lexicon/providers/internetbs.py](lexicon/providers/internetbs.py)

A typical API response for a DNS record list looks like:
```
{
  "transactid": "06f52f158aa9b391b71e6b3356e0ab0d",
  "status": "SUCCESS",
  "total_records": 1,
  "records": [
    {
      "name": "w752.test-api-domain7.net",
      "value": "111.111.111.111",
      "ttl": 3600,
      "type": "A"
    }
  ]
}
```

But when there are no records:
```
{
  "transactid": "06f52f158aa9b391b71e6b3356e0ab0d",
  "status": "SUCCESS",
  "total_records": 0
}
```

The internetbs.py provider accesses the 'records' key and thus fails with an unhandled exception, when there are no records:
https://github.com/AnalogJ/lexicon/blob/cd747b572fba8ac719556a30d69b03194af600e1/lexicon/providers/internetbs.py#L91

A simple bugfix possibility could be a conditional return just before trying to access the 'records' key:
```
if payload['total_records'] == 0:
    return []
record_list = payload['records']
```

**Comment by yearski** [comment]
I went to submit a pull request and notice that there is some inconsistencies... Should _list_records() check the 'status' attribute like the other methods do? I don't think the other methods a prone to accessing a non-existent 'records' key but it might be worth an extra set of eyes.

**Comment by AnalogJ** [comment]
Closing this issue, fix was merged
