### ISSUE TITLE
Add Linode to the project's Github tags

### ISSUE THREAD

**Issue by displague** [AnalogJ/lexicon#397]
Linode is missing from the project's tags:

![image](https://user-images.githubusercontent.com/317653/56080810-a1782900-5dd3-11e9-8033-08be5a388de5.png)

Is there a limit?

**Comment by AnalogJ** [comment]
yeah, theres a limit of 20 tags. I'm going to close this as a `wont-fix` for now, as there's not much we can do here.

At some point we'll need to consider how we decide which providers are added to that list, but TBH I'm not sure it's even used very often.
