### ISSUE TITLE
Case should be ignored when filtering records from digitalocean API

### ISSUE THREAD

**Issue by jokester** [AnalogJ/lexicon#40]
I noticed that digitalocean's HTTP API always returns `data` field of TXT records in lowercase, see [example](https://gist.github.com/jokester/e1152fd90ace2f71d767af1d96d802dc).

This can cause [lexicon](https://github.com/AnalogJ/lexicon/blob/b278cebf3f0cfba720b87b6ff9415969d524edc2/lexicon/providers/digitalocean.py#L58) to filter out the correct record and throw `Record identifier could not be found`.

Also [this error in issue #35](https://github.com/AnalogJ/lexicon/issues/35#issuecomment-213105616) seems to be related.

**Comment by jokester** [comment]
Wrote a patch [here](https://github.com/jokester/lexicon/tree/digitalocean-ignore-content-case) that solved my error.

**Comment by jokester** [comment]
Digital Ocean stuff just told me "As DNS is case insensitive, the returned value from the API vs the query result should not matter or affect the value of the query. ". That makes this patch look quite valid to me.

**Comment by AnalogJ** [comment]
ahh, that's interesting. I'll test it out locally and then merge the PR.
