### ISSUE TITLE
Unable to use easyDNS sandbox API endpoint

### ISSUE THREAD

**Issue by HanSooloo** [AnalogJ/lexicon#424]
I just got my easyDNS sandbox API access.  However, I am unable to tell lexicon to use the test endoint.

easyDNS requires me to do a "few test runs" on the sandbox environment before granting me access to the live environment.

How can I tell what endpoint URL to use?

**Comment by adferrand** [comment]
Hello! It seems the relevant command flag is missing for easyDNS. I will correct that quickly.

In the mean time, you can still set the endpoint to use by filling the environment variable `LEXICON_EASYDNS_API_ENDPOINT` before calling Lexicon.

**Comment by AnalogJ** [comment]
`LEXICON_EASYDNS_API_ENDPOINT` should work for this use-case. Closing this issue for now.
If that doesn't work @HanSooloo feel free to re-open this issue.
