### ISSUE TITLE
DNS Made Easy needs retry logic, to recover from rate limiting errors

### ISSUE THREAD

**Issue by alexzorin** [AnalogJ/lexicon#437]
Originally certbot/certbot#7411.

DNS Made Easy has [restrictive rate limits](https://api-docs.dnsmadeeasy.com/?version=latest#f6f3c489-422d-4cf0-bccb-1933e6d655ac):
>To prevent unwanted flooding of the API system, there is a maximum number of requests that can be sent in a given time period. This limit is 150 requests per 5 minute scrolling window

Lexicon should be able to recover from hitting the rate limit without failing the operation.

The response received is an HTTP 400 with a response body of:

>{"error": ["Rate limit exceeded"]}

@adferrand suggested retry logic in [this comment](https://github.com/certbot/certbot/issues/7411#issuecomment-536438100):

>How about defining a short sleep (like 5 seconds), and a retry strategy with a max attempts, triggered in case of 400 with body {"error": ["Rate limit exceeded"]}?

**Comment by adferrand** [comment]
> @adferrand I have some DME sandbox credentials you can use which has certbot-dnsmadeeasy-test.ga's DNS hosted with it - how can I send them to you?

I think the best is to send them to me as PM on EFF Mattermost.
