### ISSUE TITLE
Easyname provider is broken 

### ISSUE THREAD

**Issue by o-sole-meo** [AnalogJ/lexicon#463]
Currently, easyname support is not working as the easyname website changed. There is a pull request with a working fix though: #449 

I am in the process of getting things to work so it can be merged, but in the meantime you can just apply the 2 linechanges so you can use lexicon with easyname again.

**Comment by rqelibari** [comment]
Hey @o-sole-meo,

How far are you with your fix? Maybe I can help you. If I remember correctly, I was the one implementing the `easyname` provider.
