### ISSUE TITLE
TTLs hard-coded and not even passed to providers from the command line

### ISSUE THREAD

**Issue by geekuality** [AnalogJ/lexicon#49]
I just started to use lexicon with acme.sh and after banging my head to the wall for a while (and even suspecting that DNS Made Easy's API was not working properly as my records kept being generated with TTL of 84600 no matter what I did) before I realized to check the sources here - and, lo and behold, for example here..

https://github.com/AnalogJ/lexicon/blob/067f7feecaf2b79222374804f02b03ecdd4aa347/lexicon/providers/dnsmadeeasy.py#L37

..the value of TTL really is hard-coded to 84600 (value varies in other providers).

_(Not that I should need to explain my frustration, but that isn't very good for example for TXT records that are only very infrequently queried (so short TTL does not matter) but in the case of errors really do need to be able to be fixed quicker than that as processing the certificates via ACME protocol is highly automated and things can go wrong sometimes - mostly because of user errors.)_

Also, the value from `--ttl` is never even passed to the providers (that also are not prepared to receive it) when creating or updating the record, as seen here:

https://github.com/AnalogJ/lexicon/blob/067f7feecaf2b79222374804f02b03ecdd4aa347/lexicon/client.py#L28

..and here:

https://github.com/AnalogJ/lexicon/blob/067f7feecaf2b79222374804f02b03ecdd4aa347/lexicon/providers/dnsmadeeasy.py#L32

This seems like a pretty elementary bug to me, maybe somebody lost their train of thought while implementing this parameter? :)

**Comment by AnalogJ** [comment]
woah, thats definitely a bug. Let me write some test cases for the existing and I'll get that fixed.

**Comment by AnalogJ** [comment]
Hey @geekuality I've opened a PR with the TTL related fix. It should be packaged momentarily. Thanks for bringing up this issue, it's definitely something that was overlooked.

**Comment by AnalogJ** [comment]
fixed in version v1.1.9
