### ISSUE TITLE
Hetzner domain "robot" provider obsolete

### ISSUE THREAD

**Issue by l0rn** [AnalogJ/lexicon#491]
Hetzner recently changed their HTML web based DNS management for a new one that actually has an API. Without testing it I assume that the DNS provider making use of scraping that now discontinued web form is now obsolete.

If inteded usage is for certbot though, you can use [our plugin](https://github.com/ctrlaltcoop/certbot-dns-hetzner).

I just realize it'd probably be cool to extend our Hetzner API client and merge it into this project, hm?

**Comment by Hooorny** [comment]
vote for this

**Comment by adferrand** [comment]
Hello @l0rn! Clearly I would appreciate a lot seeing the Hetzner provider migrated from this horrible HTML scraping to a proper API!

Indeed to construct on your plan, the API logic could be hold by Lexicon, and your plugin could re-implement the logic through the dedicated class in certbot project for lexicon-based DNS plugins (https://github.com/certbot/certbot/blob/master/certbot/certbot/plugins/dns_common_lexicon.py).

What do you think of that ? I can participate with this migration: in particular if you do not have the time to rewrite the Hetzner provider in Lexicon, I can do it, if you give me API credentials to test this out against the live Hetzner API.

**Comment by l0rn** [comment]
I will take a shot in develop the Hetzner provider, gonna come back if i got questions

**Comment by l0rn** [comment]
Alrighty, happy to have someone looked at #492

**Comment by hetzner** [comment]
Just want to make clear a few things before you remove something you might need...

It is true that there is a public API available for DNS. It replaces the old 'mail interface' and one part of the GUI (that one at robot.hetzner.com) but not the GUI for webhosting clients (that one on konsoleh.your-server.de).

For the webhosting part you still need to scrape HTML. There might be some smaller changes at the params since last week.

**Comment by l0rn** [comment]
In regards to #493 i would opt for purging hetzner web-scraping providers completely from the codebase as  they are all dysfunctional at the moment. The konsoleH provider possibly could be fixed, but I don't think the effort is worth it, as web forms tend to change, and the implementation is quite flaky.

If the maintainers agree on that I could delete the konsoleH provider in this PR, or if someone would like to fix it, it'd need to be a subject of a future PR

**Comment by adferrand** [comment]
We can close this issue, since we removed the old hetzner provider.
