### ISSUE TITLE
CircleCI is misconfigured

### ISSUE THREAD

**Issue by Jamim** [AnalogJ/lexicon#508]
Hello,

I've just submitted #507 and found that one of the checks failed due to CircleCI is not configured properly.
> No configuration was found in your project.

Would you mind disabling CircleCI in order to make it more obvious whether a PR passes all checks?

Thanks!

**Comment by adferrand** [comment]
@AnalogJ, could you disable the CircleCI config? By the same occasion, it would be great to do the same for AppVeyor.

**Comment by adferrand** [comment]
In the mean time, I merged to master a proper CircleCI config. It is just a dummy Hello World!, but it will avoid to have a failure in the GitHub checks.

**Comment by Jamim** [comment]
@AnalogJ disabled the CircleCI, so this issue is resolved now.
Thank you @adferrand and @AnalogJ!
