### ISSUE TITLE
Add Dreamhost API support

### ISSUE THREAD

**Issue by bdeprez** [AnalogJ/lexicon#56]
Hi AnalogJ,

I have been looking at lexicon and your blog posts about using Let's Encrypt for private (firewalled) servers. However, I'm lost at how I could include Dreamhost support - I've been looking at the config files for the other providers but wasn't able to decypher how I would need to create one from scratch...

Dreamhost API details are here: https://help.dreamhost.com/hc/en-us/articles/217555707-DNS-API-commands

Any advice you could give me where to start?
Thanks a heap in advance!!

**Comment by techtonik** [comment]
Reuse https://github.com/mcgid/python-dreamhostapi

**Comment by AnalogJ** [comment]
Hey @bdeprez,
Basically all you need to do is create a new python file in the [providers folder](https://github.com/AnalogJ/lexicon/tree/master/lexicon/providers) with the name dreamhost.py

It needs to implement the following functions: https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/base.py#L7-L31

Looking at the dreamhost api doc you linked, it seems the response isn't JSON or XML, so you'll need to parse it yourself or use the `python-dreamhostapi` library that @techtonik linked. 

If you open up a basic PR with working auth I can walk you through the implementation. I don't have a Dreamhost account so I can't test it myself.

**Comment by Lewiscowles1986** [comment]
Interested in seeing this even though dreamhost has their own automated letsencrypt offering it would be nicer to control it from my PC and use DNS instead of magic files inside site root

**Comment by bdeprez** [comment]
Although I was able to get something working (using a different piece of code), Dreamhost’s DNS replication was too slow to get a valid response back in a reasonable amount of time – so I abandoned that solution with Dreamhost…

**Comment by Lewiscowles1986** [comment]
probably why they are not using DNS validation tbf. The second thing I considered is that many shared hosting users also move their DNS elsewhere so that could also be a problem.

**Comment by AnalogJ** [comment]
even cloudflare had a bit of a delay before new dns records were propagated. The example dehydrated [hook script](https://github.com/AnalogJ/lexicon/blob/master/examples/dehydrated.default.sh#L18) includes a 30 second delay currently, but that could potentially be parameterized so that longer delays are supported for other providers. 

How long did it take during your testing for Dreamhost records to be correctly updated?
