### ISSUE TITLE
Unable to modify Hover-based domains.

### ISSUE THREAD

**Issue by snarke** [AnalogJ/lexicon#616]
Hover appears to have changed their undocumented API since the last time Lexicon was updated. 

in /providers/hover.py, line 45 currently is 

` "https://www.hover.com/signin/auth.json", json=payload, cookies=self.cookies
`

My installation of Lexicon started working normally again when I changed this line to 

`"https://www.hover.com/api/login/", json=payload, cookies=self.cookies
`

**Comment by DVE2000** [comment]
Thanks for leaving a solution!

**Comment by adferrand** [comment]
Thanks a lot. Do not hesitate to open a PR!

**Comment by snarke** [comment]
You're welcome. What's a PR?

**Comment by snarke** [comment]
Huh. "Edit" doesn't work. Okay, I'm guessing a "PR" is a Pull Request. I looked there, and it says "If you know how to fix an issue, consider opening a pull request for it.
You can read this repository’s _contributing guidelines_ to learn how to open a good pull request."

I followed the Contributing Guidelines link. They said simply "Here's the Developer's Guide." 

The Developer's Guide quickly launched into explaining that I could fork the repository, and, well, lots of other stuff that made my eyes glaze over. I don't do GitHub. I don't do Python. I'm not a serious programmer. I'm a composer and artistic engineer who likes Ruby and has run his own servers from home for 22 years.  

So I regret to admit I'm absolutely hesitating before opening a PR. Sorry.

**Comment by DVE2000** [comment]
You can't edit in someone else's repository. And branches don't really matter here. Because this is such a simple change, the steps can all easily be done via your browser. You fork the repository to your own space and you find the file there and edit it. Saving is a "git commit", which requires a comment. And then you click the New Pull Request button. I just did this and created a PR.

**Comment by adferrand** [comment]
This is been fixed with #618
