### ISSUE TITLE
Add support for porkbun

### ISSUE THREAD

**Issue by petermetz** [AnalogJ/lexicon#667]
https://porkbun.com/

**Comment by adferrand** [comment]
Hello, implementing a provider on Lexicon require a documentation of an API that the tool can reach to modify DNS records in the DNS zone. Does porkbun have any of this?

**Comment by petermetz** [comment]
> Hello, implementing a provider on Lexicon require a documentation of an API that the tool can reach to modify DNS records in the DNS zone. Does porkbun have any of this?

@adferrand As I just learned from their customer support they unfortunately do not have an API => Closing the issue. Thanks for responding!

**Comment by EnorMOZ** [comment]
Unofficial client for the Porkbun API - https://pypi.org/project/pkb-client/
Porkbun API - https://porkbun.com/api/json/v3/documentation#Authentication

**Comment by petermetz** [comment]
@EnorMOZ Thank you, I think this warrants a reopen.

**Comment by EnorMOZ** [comment]
Looks lime there is a certbot plugin as well.

https://pypi.org/project/certbot-dns-porkbun/

**Comment by juanalbglz** [comment]
hello @porkbun any light here?
