### ISSUE TITLE
Get all domains

### ISSUE THREAD

**Issue by mgclabs** [AnalogJ/lexicon#678]
I've been reading through the documentation and code, trying to figure out how to get a list back of all domains in Route53, is this possible with Lexicon?

**Comment by adferrand** [comment]
Lexicon is dedicated to modifying the DNS entries of zones, but not the DNS zones themselves. So there is no API to work with them directly.

**Comment by anderspitman** [comment]
@adferrand are you aware of any project that has this functionality?
