### ISSUE TITLE
Extra "dev"

### ISSUE THREAD

**Issue by MasinAD** [AnalogJ/lexicon#686]
I'm stupid, so please be patient with me.

I follow the developer guide for setting up my dev environment but on

```
pip install -e .[full,dev]
```
I get, besides regular progress messages, the warning
```
 WARNING: dns-lexicon 3.5.3 does not provide the extra 'dev'
```

Last year, when I did this, I had a `lexicon` executable in my [venv]/bin/ but this time I don't and I guess this is linked to the extra [dev] missing.

Python is still unfamiliar to me as is working with setuptools. I guess the different "extras" are defined in `pyproject.toml` as at least the [full] extra seems to be there. But there's a whole tool chain plumbed together that are quite arcane for the aspiring beginner Python developer  :-).

**Comment by MasinAD** [comment]
I finally got it into a state in which I assume I can develop by issuing
```
pip install poetry
pip install -e file:///<fullpathtolocalrepo>#egg=dns-lexicon[full]
# cd into local repo
poetry install
```
I can only assume that this last step should be done by pip (v20.3.3), but maybe it won't because of my Python 3.9 as there is a statement in the pyproject.toml
```
[tool.poetry.dependencies]
python = "^3.6"
```
If I read this correctly this is any Python version where the version string starts with 3.6. … *search* nope, [I read this wrongly](https://python-poetry.org/docs/versions/).

Whatever I did to make it work it was just lucky guessing. I saw the "full" extra requirements in a section labeled `tool.poetry[…]` so I assumed there needed to be a tool of this name being involved. In `pip list` I have this entry:
```
UNKNOWN           0.0.0     /home/masin/Projekte/dns/lexicon
```
which made me think to tell pip to use my local repository for providing dns-lexicon as a dependency if needed somewhere. I don't know if it works this way as there's still another `dns-lexicon` entry. And `poetry install` was just an attempt to see if something happens which should have happened on `pip install -e[…]`.

FWIW, the docs should be updated accordingly. And maybe in a way that's not so … improvised as mine :laughing:

**Comment by adferrand** [comment]
Hello @MasinAD! Yes very sorry for the not up-to-date documentation. I will rewrite it using poetry directly so that everything is set up with minimal manual actions.

**Comment by adferrand** [comment]
Oh. In fact, I already did that! But for some reason the documentation on readthedoc is not updated.
