### ISSUE TITLE
dnsmadeeasy help

### ISSUE THREAD

**Issue by habnai** [AnalogJ/lexicon#72]
i want use acme.sh with dnsmadeeasy but how insert api key and use it for auth i use like example of cloudflare but not work?

**Comment by bombergio** [comment]
To get dnsmadeeasy working you would need to provide:
--auth-username="<your API key from DNSMadeEasy>" --auth-token="<your Secret Key from DNSMadeEasy>"

If you prefer to use ENV, then:
export LEXICON_DNSMADEEASY_USERNAME="<your API key from DNSMadeEasy>"
export LEXICON_DNSMADEEASY_TOKEN="<your Secret Key from DNSMadeEasy>"

You can obtain both API Key and Security token (or generate if not done previously) in your account page: https://cp.dnsmadeeasy.com/account/info

**Comment by Neilpang** [comment]
Hi,  @habnai 

acme.sh has local support for DNSMadeEasy  now:

https://github.com/Neilpang/acme.sh/tree/master/dnsapi#use-dnsmadeeasy-domain-api

**Comment by habnai** [comment]
Good work. Thank you

**Comment by wizonesolutions** [comment]
acme.sh was the only thing that worked for me with DNS Made Easy. Not lego, not dehydrated + letsencrypt-DNSMadeEasy-hook, not dehydrated+lexicon. But acme.sh worked fine. Impressed.

**Comment by AnalogJ** [comment]
Hey @wizonesolutions 
What issues were you running into with dehydrated+lexicon? I'd like to fix the issue if possible.

**Comment by wizonesolutions** [comment]
@AnalogJ In `lexicon` itself, `dnsmadeeasy` is broken again, at least when using environment variables to set the username and token. I guess `create_record: False` or something like that. Hope that helps.
