### ISSUE TITLE
Setup a development environment outdated

### ISSUE THREAD

**Issue by jlongua** [AnalogJ/lexicon#731]
pip install -e .[full,dev]
ERROR: Package u'dns-lexicon' requires a different Python: 2.7.16 not in '>=3.6,<4.0'

sure enough: https://pypi.org/project/dns-lexicon/

License: MIT License (MIT)
Author: Jason Kulatunga
Tags dns, lexicon, dns-lexicon, dehydrated, letsencrypt
Requires: Python >=3.6, <4.0

Python 2.7 reached the end of its life on January 1st, 2020
pip 21.0 will drop support for Python 2.7 in January 2021

**Comment by adferrand** [comment]
Indeed, it seems that you are trying to install lexicon using a Python 2 distribution. You should use Python 3.6 at minimum.

Also, be sure to use the most up-to-date instructions to setup a development environment. Lexicon now uses Poetry: https://dns-lexicon.readthedocs.io/en/latest/developer_guide.html#setup-a-development-environment

**Comment by jlongua** [comment]
thanks, this guide worked for me.
