### ISSUE TITLE
Add INWX API

### ISSUE THREAD

**Issue by killerbees19** [AnalogJ/lexicon#74]
Basic implementation: https://github.com/inwx/python2.7-client

**Comment by AnalogJ** [comment]
Hey @killerbees19 
I'm willing to add it, but unfortunately it seems that `inwx` requires a paid account. If you're wiling to be a guinea pig, I can try and throw something together, but I'll have to be next week (I'm traveling at the moment).

If you open a PR, I'll be happy to merge it.

**Comment by AnalogJ** [comment]
Hey @killerbees19 
I'm going to close this issue, but feel free to open a PR at any time.
