### ISSUE TITLE
CloudNS

### ISSUE THREAD

**Issue by ghub2015** [AnalogJ/lexicon#79]
@AnalogJ, I created a working version for CloudNS (cloudns.net) API, how would you like it contributed?

(I ask because when I looked [here](https://github.com/AnalogJ/lexicon/pull/78), you said you were traveling and you will add a doc specifying how developers can write and test their own providers.)

I have been using my CloudNS version in production for numerous domains without issue.

Please let me know.

Thank you

**Comment by AnalogJ** [comment]
Hey @ghub2015 
I really didn't mean to ignore your PR. I was working on a deployment all week and I'll be travelling again this weekend. I should have some more time next week to put together a more comprehensive guide on how to test with Lexicon. 

However don't let that stop you. If you already have a working provider, **please** contribute it :) 
The guide I'm writing will be for devs who aren't familiar with pip and how to run the lexicon executable from checked-out source code (`pip install -e .`)

**Comment by AnalogJ** [comment]
Hey @ghub2015 
I was finally able to write up a guide for contributing to `lexicon`

https://github.com/AnalogJ/lexicon/blob/master/CONTRIBUTING.md

Can you take a look and open an issue if there's anything missing?

I'd love to see CloudNS support added to `lexicon`

**Comment by ghub2015** [comment]
@AnalogJ, will do.  (Sorry I didn't get any notification about your update, I just happened to browse and see your update)

My implementation has been working great for me with CloudNS so I would really like to contribute it.

**Comment by AnalogJ** [comment]
:) Looking forward to it

**Comment by AnalogJ** [comment]
Hey @ghub2015 Is there any help you need to get `CloudNS` added?
