### ISSUE TITLE
Unable to create record for delegated subdomain

### ISSUE THREAD

**Issue by michaeltravisuk** [AnalogJ/lexicon#80]
I am able to use Lexicon to create records on our top level domain (`platformservices.io`) which is hosted by Gandi, but not our delegated subdomains, hosted in Route53.

I get error `StandardError: No domain found`

Looking at the Route53 provider, it loops through Route53 zones it has found to see where your domain fits:

https://github.com/AnalogJ/lexicon/blob/master/lexicon/providers/route53.py#L94

But the way the domain name is being parsed means it never gets matched.  I added a print line to show the domain it was trying to match to and it showed` platformservices.io.`

The zone in Route53, however is `euw.platformservices.io`, so the `euw` is being stripped in order to find the zone name.

**Comment by AnalogJ** [comment]
Hey,
I don't have a route53 associated domain to test with right now. I can add one and do some testing, but that could take some time. Any chance you could throw together a PR with a fix?

**Comment by michaeltravisuk** [comment]
Added PR to allow matching against either domain or subdomain on Route53:
https://github.com/AnalogJ/lexicon/pull/82

**Comment by brianwells** [comment]
I'm running into the same issue with subdomains delegated to NS1 (nsone) and will see if I can adapt the fix that @michaeltravisuk devised for Route53.

**Comment by AnalogJ** [comment]
Sorry it's taken so long to back to this issue. I see what you mean now. 

Basically I made some incorrect assumptions when designing lexicon. Specifically that the DNS services would be hosting top-level domains. I didn't take into account delegated subdomains. 

While your PR does work, I want to see if there's a way I can create a general purpose solution for all DNS providers, without breaking the existing cli.

Thanks for pointing this out.

**Comment by brianwells** [comment]
@AnalogJ: For your review I've submitted a pull request (#97) that may fix delegated subdomains for all the DNS providers.

**Comment by AnalogJ** [comment]
This can be closed now that I've merged @brianwells's PR. Version v1.2.3 of `lexicon` has been released with support for delegated domains.
