### ISSUE TITLE
'No domain found' on Ubuntu for Cloudflare

### ISSUE THREAD

**Issue by qnxor** [AnalogJ/lexicon#81]
I'm on Ubuntu 14.04.3 and have installed the prerequesites (`pip install --upgrade requests[security]` then `pip install dns-lexicon`), then downloaded your latest `dehydrated.default.sh` script and placed it in `hooks/lexicon/lexicon.sh` in the latest cloned dehydrated package. 

Then I did:
```
# export PROVIDER=cloudflare
# export LEXICON_CLOUDFLARE_USERNAME=<MY_CF_EMAIL_LOGIN>
# export LEXICON_CLOUDFLARE_TOKEN=<MY_CF_API_KEY>
# dehydrated/dehydrated -c -t dns-01 -d DOMAIN.TLD -d mail.DOMAIN.TLD -d www.DOMAIN.TLD -k dehydrated/hooks/lexicon/lexicon.sh
```

And it spits the following:

```
#
# !! WARNING !! No main config file found, using default config!
#
Processing DOMAIN.TLD with alternative names: mail.DOMAIN.TLD www.DOMAIN.TLD
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for DOMAIN.TLD...
 + Requesting challenge for mail.DOMAIN.TLD...
 + Requesting challenge for www.DOMAIN.TLD...
deploy_challenge called: DOMAIN.TLD, Gm1Xu2MFiLes5LrjumDDWef0CiNj32Dqt5j8LX0JmMU, Za3K2rD4SkrriVceCbDMm_KXIPoc08rx42NTQS2ENZw
Namespace(action='create', auth_token=None, auth_username=None, content='Za3K2rD4SkrriVceCbDMm_KXIPoc08rx42NTQS2ENZw', domain='DOMAIN.TLD', identifier=None, name='_acme-challenge.DOMAIN.TLD.', priority=None, provider_name='cloudflare', ttl=None, type='TXT')
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==1.1.20', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 52, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 25, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/cloudflare.py", line 24, in authenticate
    raise StandardError('No domain found')
StandardError: No domain found
```

Didn't look in your python code myself yet.

**Comment by qnxor** [comment]
Just for the record, this hook for cloudflare works fine: https://github.com/kappataumu/letsencrypt-cloudflare-hook

**Comment by qnxor** [comment]
Same error if I try the CLI directly:

```
# lexicon cloudflare --auth-username CF_EMAIL --auth-token CF_API_KEY list DOMAIN.TLD TXT
Namespace(action='list', auth_token='CF_EMAIL', auth_username='CF_API_KEY', content=None, domain='DOMAIN.TLD', identifier=None, name=None, priority=None, provider_name='cloudflare', ttl=None, type='TXT')
Traceback (most recent call last):
  File "/usr/local/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==1.1.20', 'console_scripts', 'lexicon')()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/__main__.py", line 52, in main
    client.execute()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/client.py", line 25, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/lexicon/providers/cloudflare.py", line 24, in authenticate
    raise StandardError('No domain found')
StandardError: No domain found

```

Whereas querying cloudflare directly via curl works fine

```
# curl https://www.cloudflare.com/api_json.html -d 'a=rec_load_all' -d 'tkn=CF_API_KEY' -d 'email=CF_EMAIL' -d 'z=DOMAIN.TLD'
{"request":{"act":"rec_load_all"},"response":{"recs":{"has_more":false,"count":17,"objs":[{"rec_id":
....
}
```
Listing my full domain DNS records details.

Seems there is a bug somewhere

**Comment by AnalogJ** [comment]
I use cloudflare almost exclusively for a lot of my Letsencrypt domains, so I'm surprised that you're running into issues. 
The only difference I noticed is that it like you're passing in multiple domains at the same time. While that **shouldn't** cause any issues, it's not a use case that I've tested very heavily. 

I'll update you once I replicate your issue.

**Comment by qnxor** [comment]
The last post (just above yours) is using the CLI version of your tool to do a simple query on the domain and that fails too, whereas directly querying via curl works fine. Not sure where the bug is. Could CF have updated anythign on their end?

**Comment by AnalogJ** [comment]
Hey @qnxor 

I just ran the command and got a successful response:

> $ lexicon cloudflare --auth-username XXXXXX --auth-token XXXXXX list capsulecd.com TXT
Namespace(action='list', auth_token='XXXXXX', auth_username='XXXXXX', content=None, domain='capsulecd.com', identifier=None, name=None, priority=None, provider_name='cloudflare', ttl=None, type='TXT')
> 
> list_records: [{'content': u'ttlshouldbe3600', 'id': u'd8228669d592e95dae643af3f02b3121', 'type': u'TXT', 'name': u'ttl.fqdn.capsulecd.com', 'ttl': 3600}, {'content': u'ttlshouldbe500', 'id': u'404c3e5c08b801c1ad6fe6e451a39a29', 'type': u'TXT', 'name': u'ttlrecord.fqdn.capsulecd.com', 'ttl': 500}]
>
> $ lexicon --version
> lexicon 1.1.20

Can you confirm that your `DOMAIN.TLD` example is a top level domain, and is correctly registered with CloudFlare?

**Comment by qnxor** [comment]
Yes, see the direct curl call I posted above which is successful.

**Comment by AnalogJ** [comment]
Hey @qnxor 
Can you verify that you can use the v4 version of the cloudflare api with your token?
I noticed that you were using an older version of their api in your manual call, and I'm wondering if your API token doesn't work with the version that lexicon uses. 


```
curl -X GET "https://api.cloudflare.com/client/v4/zones?name=example.com&status=active&page=1&per_page=20&order=status&direction=desc&match=all" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: 123456ABCDEFG" \
     -H "Content-Type: application/json"
```

**Comment by qnxor** [comment]
Yep, works fine:
```
# curl -X GET "https://api.cloudflare.com/client/v4/zones?name=DOMAIN.com&status=active&page=1&per_page=20&order=status&direction=desc&match=all"      -H "X-Auth-Email: USER@EMAIL.COM"      -H "X-Auth-Key: <API_KEY>"      -H "Content-Type: application/json"
{"result":[{"id":"<DOMAIN_ID>","name":"DOMAIN.com","status":"active","paused":false,"type":"full","development_mode":0,"name_servers":["coco.ns.cloudflare.com","will.ns.cloudflare.com"],"original_name_servers":["ns.123-reg.co.uk","ns2.123-reg.co.uk"],"original_registrar":null,"original_dnshost":null,"modified_on":"2017-01-19T02:44:57.357779Z","created_on":"2017-01-17T15:45:52.233780Z","meta":{"step":4,"wildcard_proxiable":false,"custom_certificate_quota":0,"page_rule_quota":3,"phishing_detected":false,"multiple_railguns_allowed":false},"owner":{"type":"user","id":"<USER_ID>","email":"USER@EMAIL.COM"},"permissions":["#analytics:read","#billing:edit","#billing:read","#cache_purge:edit","#dns_records:edit","#dns_records:read","#lb:edit","#lb:read","#logs:read","#organization:edit","#organization:read","#ssl:edit","#ssl:read","#waf:edit","#waf:read","#zone:edit","#zone:read","#zone_settings:edit","#zone_settings:read"],"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee","name":"Free Website","price":0,"currency":"USD","frequency":"","is_subscribed":true,"can_subscribe":false,"legacy_id":"free","legacy_discount":false,"externally_managed":false}}],"result_info":{"page":1,"per_page":20,"total_pages":1,"count":1,"total_count":1},"success":true,"errors":[],"messages":[]}
```
I'll try your lexicon again later and will report back

**Comment by qnxor** [comment]
lexicon now works! Exact same command as in my [2nd post](https://github.com/AnalogJ/lexicon/issues/81#issuecomment-269142121) in this thread which failed then ... we should probably write it off to a glitch somewhere else

**Comment by AnalogJ** [comment]
thats super weird. I guess I'll just close this issue then. Feel free to reopen if it happens again.
