### ISSUE TITLE
Zeit.co stopped working

### ISSUE THREAD

**Issue by Skaronator** [AnalogJ/lexicon#844]
A couple weeks ago Zeit.co stopped working. I'm using the lexicon library indirectly with dnsrobocert to renew my certificates. And I can see the following error in the Log:

```
Error while executing the `cleanup` hook:
'uid'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 40, in main
    globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/hooks.py", line 123, in cleanup
    txt_challenge(certificate, profile, token, domain, action="delete")
  File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/challenge.py", line 57, in txt_challenge
    Client(lexicon_config).execute()
  File "/usr/local/lib/python3.9/site-packages/lexicon/client.py", line 72, in execute
    self.provider.authenticate()
  File "/usr/local/lib/python3.9/site-packages/lexicon/providers/base.py", line 74, in authenticate
    return self._authenticate()
  File "/usr/local/lib/python3.9/site-packages/lexicon/providers/zeit.py", line 45, in _authenticate
    if not result["uid"]:
KeyError: 'uid'
```

This is the code that throws the error in the first place:

https://github.com/AnalogJ/lexicon/blob/db82a948febee04972bb648ac59471b292c7e394/lexicon/providers/zeit.py#L44-L47

After a bit debugging I found out that the API seems to have changed.

When doing a Request to https://api.zeit.co/v2/domains/skaronator.com

I get a response with a `id` key but no `uid` key. This is probably the main issue:

(snipped for privacy)
```json
{
  "domain": {
    "boughtAt": 123,
    "configVerifiedAt": 123,
    "createdAt": 123,
    "expiresAt": 123,
    "id": "xyz",
    "name": "skaronator.com",
    "nsVerifiedAt": 123,
    "serviceType": "zeit.world",
    "transferredAt": 123,
    "transferStartedAt": 123,
    "txtVerifiedAt": null,
    "verificationRecord": "xyz",
    "cdnEnabled": true,
    "verified": true,
    "nameservers": [ <snipped>  ],
    "intendedNameservers": [ <snipped>  ],
    "creator": { <snipped>  },
    "zone": true,
    "suffix": false,
    "aliases": [ <snipped>  ],
    "certs": [ <snipped> ]
  }
}
```

Not sure if other endpoints have changed but it would make sense to update the API to the new address since they renamed a year ago: https://vercel.com/docs/api#endpoints/domains/get-information-for-a-single-domain

**Comment by adferrand** [comment]
Hello @Skaronator I would be glad to fix the provider, however I need valid credentials and DNS zone to work against the real API. Would you agree to lend me some access to your account for that purpose? If so we can exchange privately on Signal for instance.

**Comment by Skaronator** [comment]
Hi @adferrand, saidly there is no option to limit the API token scope. So can't share my token since there is a lot of important stuff in there. The good news is that you can create an account yourself and use the included *.now.sh sub-domain for free.

**Comment by adferrand** [comment]
Ok I check that. Thanks!

**Comment by adferrand** [comment]
It seems that Zeithas been rebranded to Vercel, among with several evolutions in the API. I updated Lexicon according to these evolutions in `3.7.0`. Normally all errors are fixed given the tests I did. Do not hesitate to reopen if it is not the case.
