### ISSUE TITLE
luadns provider script breaks with default ttl

### ISSUE THREAD

**Issue by jmbromley** [AnalogJ/lexicon#87]
When leaving ttl unspecified, the script ends up calling the luadns API with the ttl parameter set as 'None' instead of the default.  This results in the call failing.  I'm creating a pull request with a fix for this.

**Comment by stompro** [comment]
Same problem with dnsmadeeasy provider.

**Comment by AnalogJ** [comment]
This should be fixed in #92 for all providers.

Can you try using version `v1.2.1`?

**Comment by stompro** [comment]
I just tested 1.2.1 on a different vm and it works with no modifications, thanks.
Josh
