### ISSUE TITLE
error: argument --content: expected one argument

### ISSUE THREAD

**Issue by welwood08** [AnalogJ/lexicon#9]
I was getting this error occasionally while creating zone entries for letsencrypt challenges. Managed to track it down to a content string beginning with a hyphen. The argument parsing library lexicon uses seems to misinterpret that as another argument rather than the value of the content argument.

Worked around it by replacing `--content "$challenge"` with `--content="$challenge"`. Not sure how easy it is to modify the usage output of argsparse, but it might be an idea to recommend this style in the acme-challenge readme examples.

**Comment by AnalogJ** [comment]
good catch. I'm in the middle of a partial rewrite of the engine to make it more testable. I'll take a look at handling CLI args better.

**Comment by AnalogJ** [comment]
Hey @welwood08 , I've released version 1.0.11 which updated the readme to use `=` when specifying parameters.
