### ISSUE TITLE
route53: boto3 should not be optional

### ISSUE THREAD

**Issue by willfarrell** [AnalogJ/lexicon#93]
I've found that `pip install dns-lexicon[route53]` does not install the required dep `boto3`. See error below. Example use/workaround can be found at https://github.com/willfarrell/docker-letsencrypt/blob/master/Dockerfile

```bash
Namespace(action='list', auth_access_key=None, auth_access_secret=None, auth_token=None, auth_username=None, content=None, domain='ductoid.com', identifier=None, name=None, priority=None, provider_name='route53', ttl=None, type='A')
Traceback (most recent call last):
  File "/usr/bin/lexicon", line 11, in <module>
    load_entry_point('dns-lexicon==1.1.20', 'console_scripts', 'lexicon')()
  File "/usr/lib/python2.7/site-packages/lexicon/__main__.py", line 51, in main
    client = Client(parsed_args.__dict__)
  File "/usr/lib/python2.7/site-packages/lexicon/client.py", line 22, in __init__
    self.provider = provider_class(self.options)
  File "/usr/lib/python2.7/site-packages/lexicon/providers/route53.py", line 80, in __init__
    self.r53_client = boto3.client(
NameError: global name 'boto3' is not defined
```

I would submit a PR, but python is a little out of my wheelhouse.

**Comment by AnalogJ** [comment]
Hey @willfarrell 
I've pulled out route53 in the recent version. I want to make sure that lexicon works in python 2.7, 3.4 and 3.5 but there were some issues with the Route53 and Gandi providers.

**Comment by willfarrell** [comment]
Thanks for the update.

Just realize pip wasn't pulling v1.2.1, so pushed an update to `willfarrell/docker-letsencrypt`. I'll watch out for new version.

**Comment by AnalogJ** [comment]
v1.2.2 should be available on pip now as well. Adds support for Yandex.
