### ISSUE TITLE
Developer guide says to run `tox -e standard` but that environment doesn't exist

### ISSUE THREAD

**Issue by quinncomendant** [AnalogJ/lexicon#963]
The developer guide's instructions to [setup a development environment](https://dns-lexicon.readthedocs.io/en/latest/developer_guide.html#setup-a-development-environment) include this step:

```
Make sure the tests pass:
$ tox -e standard
```

According to the `tox.ini` file, there is no “standard” environment, only these: `envlist = cover,lint,mypy`. 

I've run `tox -e cover` and all the tests seem to run as expected. So, perhaps someone just needs to update the documentation to change "standard" to "cover".

**Comment by adferrand** [comment]
This is fixed with `3.8.0`. Thanks !
