### ISSUE TITLE
Dreamhost integration will break November 2nd, 2021

### ISSUE THREAD

**Issue by Codelica** [AnalogJ/lexicon#974]
It looks like Dreamhost is "retiring" some of it's API calls Nov 2nd, including `domain-list_domains` which Lexicon seems to use for validating the domain during initial auth:

https://help.dreamhost.com/hc/en-us/articles/217555767-Domain-API-commands

https://github.com/AnalogJ/lexicon/blob/db82a948febee04972bb648ac59471b292c7e394/lexicon/providers/dreamhost.py#L103

They have begin sending email to anyone using the API:

> The following API commands were run on your account in the last thirty days and will no longer function after November 2nd:
> - domain-list_domains

**Comment by minj** [comment]
And... it's gone
